### ISSUE TITLE
ds3 controller deadzone issues 

### ISSUE THREAD

**Issue by AlexS2412** [cathery/sys-con#10]
luigis mansion always seems to move luigi around on ds3 controllers.

**Comment by cathery** [comment]
This is a duplicate of your previous issue. The latest release should have fixed it. Do you still have that problem?

**Comment by AlexS2412** [comment]
will test it now. i also submitted another issue about the rock candy controller?

**Comment by cathery** [comment]
I cannot support the rock candy 360 unless i can afford it. If you want to see it supported in the future, support me on my [ko-fi page](https://ko-fi.com/cathery)

**Comment by AlexS2412** [comment]
the issue is fixed :)

**Comment by AlexS2412** [comment]
if you have discord mine is 💛 𝓡𝓲𝓷 𝓚𝓪𝓰𝓪𝓶𝓲𝓷𝓮 💛#8291 , perhaps we could talk more?
