### ISSUE TITLE
Can't use it on sx os

### ISSUE THREAD

**Issue by jonathanmeenezes** [cathery/sys-con#102]
Hi, i cant use it on sx os, i renamed the "atmosphere" folder to "sxos" and replaced on my microsd, turned on my console, and nothing happens, i tried to restart, yet nothing happens, the ps4 controller keep pulsing orange light, idk what to do about, i already turned on pro controller wired communication, and nothing happens, could anyone help me?

**Comment by jonathanmeenezes** [comment]
im also with, console 9.0.1 and sx os 2.9.2

**Comment by cathery** [comment]
If you have a 2nd generation dualshock 4 controller you need to edit the global config file.

**Comment by jonathanmeenezes** [comment]
Maaaan, thats totally worked, Thanks alot, Lov u <3
