### ISSUE TITLE
1st gen Dual Schock 4 is not working

### ISSUE THREAD

**Issue by aria0012** [cathery/sys-con#105]
Only one version is supported? or am I wrong?

**Comment by cathery** [comment]
Try going to `sdmc:/config/sys-con/config_global.ini` and change the value of **use_dualshock_2nd_generation** from **false** to **true** and see if it works.

**Comment by aria0012** [comment]
Actually, this was dumb of me, I can confirm now it works even without changing the value, installing from homebrew appstore requires you to go to hekate and boot again. It works so great!
