### ISSUE TITLE
Sys-Con not working on SX-OS?

### ISSUE THREAD

**Issue by DrakeOnSwitch** [cathery/sys-con#113]
**Description**
So, I recently bought SX-OS since I am not a big fan of Atmosphere. I downloaded Sys-Con and put it into my sxos folder, I changed the contents folder to titles, and booted into sxos. I was going to use a 2nd gen Dualshock 4, so I went into the config_global.ini file and changed the Dualshock 4 value to true. Then I restarted my console. When I plugged in my Dualshock 4 through the usb port on the dock, the controller did not connect. The controller wasn't showing up in the controller section of the switch menu. I went to settings and made sure that Pro Controller Wired Communication was enabled (it was). I am not sure what the issue could be. Is Sys-Con even supported on SX-OS? A reply would be massively appreciated. 

- My switch firmware version is 8.10
- My version of Sx OS is 2.93
- My version of sys-con is 0.52
- Other sysmodules I have enabled are sys-clk and sys-ftpd

**Comment by david4444** [comment]
Only thing I can think of is maybe you're using too much memory. Try using sys-ftpd-light, or just don't use any version of sys-ftpd. It should work fine on SX OS.

**Comment by DrakeOnSwitch** [comment]
> Only thing I can think of is maybe you're using too much memory. Try using sys-ftpd-light, or just don't use any version of sys-ftpd. It should work fine on SX OS.

Ok, thanks for the help.

**Comment by DrakeOnSwitch** [comment]
Strangely, deleting sys-ftpd did not fix my issue at all. I might need to search for different solutions.

**Comment by DrakeOnSwitch** [comment]
I have also tried booting into Atmosphere and even ReiNX, nothing works

**Comment by cathery** [comment]
sys-con 0.5.2 was released for Atmosphere 0.10.0+. Since this is SX OS, i'm guessing you would want to put the sysmodule into the `titles` folder instead of `contents`.

**Comment by cathery** [comment]
I can guarantee it works on Atmosphere though, maybe you should check if you've installed it properly.

**Comment by cathery** [comment]
Also, if you can, try plugging in a different controller. Using a non-working dualshock 4 as evidence is shaky at best. All the changes to config files are updated immediately.

**Comment by DrakeOnSwitch** [comment]
Ok, I will try these solutions. Thanks.

**Comment by lucasmartiliano** [comment]
i am experiencing the same problem, i use sx os and i am trying to connect a zero delay card and i am not getting
