### ISSUE TITLE
Xbox One Controller Deadzones

### ISSUE THREAD

**Issue by PranavSakthivel** [cathery/sys-con#114]
With the xbox one controller, the deadzones seem a bit too sensitive. These controllers are known for stick drift issues, would it be possible to up the deadzones a little bit for these controllers? In games like Luigi's Mansion 3, Luigi moves slightly all the time due to the stick being slightly off center when untouched. Thanks.

**Comment by cathery** [comment]
You can change them in `sdmc:/config/sys-con/`. There's a config file for each type of controller.
