### ISSUE TITLE
cant get anything working controller wise.

### ISSUE THREAD

**Issue by soniciso** [cathery/sys-con#117]
**Description**
im not sure if im doing something wrong or what? im on atmosphere 9.1.0 with sigpatches running fusee primary... i copied over sys-con 052 files and boot switch and try using controllers... nothing ever works. am i missing something here?

**How to reproduce**
1. followed instructions on site to just drag and drop and plug and play

**Environment**
- 9.1.0
- 0.10.1
- 052
- no

**Comment by cathery** [comment]
Can't reproduce.

**Comment by soniciso** [comment]
ive tried even just fresh putting the cfw files and starting from scratch (not from sdsetup.com but from sciresm github). no avail... not sure why it does it... i wanna try it on my girlfriends switch and see if i have any luck,

**Comment by soniciso** [comment]
if you dont mind me asking... which cfw and payload are you using?

**Comment by cathery** [comment]
Please describe what controllers you used before submitting the bug report. Right now sys-con supports Dualshock 3, Dualshock 4 (first gen by default), and XInput devices.

**Comment by soniciso** [comment]
ive tried first gen xbox one, first gen ps4, and original xbox controller s

**Comment by cathery** [comment]
I have Atmosphere 0.10.1, hekate 5.1.1, running on firmware 9.1.0. Everything works as usual when booting through either fusee-primary or hekate. I have an Xbox One controller S, which, when updated to latest xbox firmware, stops working in docked mode. I also have a second gen DS4 which requires you to change a setting before it is recognized.

**Comment by soniciso** [comment]
hmm... anything special need to be done to original xbox controller s? because those didnt get firmware updates or anything like that...

**Comment by cathery** [comment]
No, it just needs to be plugged in.

**Comment by cathery** [comment]
You would get a notification about a controller update when plugging it in to your Xbox One, or when using Xbox Accessories on Windows 10.

**Comment by soniciso** [comment]
thats odd... idk ill try fresh installing atmosphere again in the morning... if anything ill try my girls switch. btw when i update i usually update my switces the nintendo way and let it blow fuses and whatnot... that wouldnt be part of the issue would it?

**Comment by cathery** [comment]
The only requirement for sys-con is running Atmosphere.

**Comment by soniciso** [comment]
idk its odd... it seems like it just wont load it period... ill try maybe loading a dif module see if that works. i will download ftpd or something and give it a whirl.im sure ill eventually figure it out. anyways, thank you for your work and have a happy holidays.
