### ISSUE TITLE
A” and “b” switched on wired switch controller

### ISSUE THREAD

**Issue by crakshay** [cathery/sys-con#118]
**Description**
“A” and “b” button switched on official wired switch usb controller

**Environment**
- latest Sys con, latest SXOS, 9.0.1

Please let me know if you need anymore information

**Comment by cathery** [comment]
I do need more information. Is it a Nintendo Switch Pro Controller? Does it happen without sys-con enabled? Did you modify any keys in the config files?
I'm asking because sys-con does not touch Pro Controllers whatsoever.

**Comment by crakshay** [comment]
It is a hori GameCube style usb controller, “officially licensed by Nintendo switch - Zelda”

Have not modified any keys in the config. I can try to disable Sys con - just not sure how to do that. Do I just delete the file from my sd?

>> Akshay A. Chhana  
>> UT Health San Antonio
>> D.D.S. Candidate 2021

**Comment by cathery** [comment]
Can you send me the log located at `sdmc:/config/sys-con/log.txt`? Also, to disable sys-con, you can go to `sdmc:/atmosphere/contents/690000000000000D/flags` and delete/rename `boot2.flag` and reboot your switch.

**Comment by crakshay** [comment]
> Can you send me the log located at `sdmc:/config/sys-con/log.txt`? Also, to disable sys-con, you can go to `sdmc:/atmosphere/contents/690000000000000D/flags` and delete/rename `boot2.flag` and reboot your switch.

Hey I am no longer having this problem after restarting my switch.. thank you for your speedy replies to help troubleshoot my problem. I appreciate awesome developers like you!
