### ISSUE TITLE
Xbox 360 and Xbox ONE controller not working

### ISSUE THREAD

**Issue by mxswat** [cathery/sys-con#119]
**Description**
I just updated my switch to 9.1.0 from 8.1.0 and before from 5.0.1 and the sys-con is not working at the moment.

I was using Firmware 5.0.1 with ReiNX and It was working perfectly with my custom dock using 0.5.2 - Atmosphere 0.10

Now I'm on 9.1.0 with Atmosphere 0.10.1 and still using the unofficial dock.

(maybe Atmosphere **0.10.1** is the problem? I'm Assuming 0.10.1 adds only minor changes)

**Controller Infos:**
Xbox 360 not original but was working on the previous version
Xbox One wireless controller w/ USB cable but was working on the previous version

**Current Environment**
- Switch Firmware version => 9.1.0
- version of Atmosphere => 0.10.1
- version of sys-con => 0.5.2 - Atmosphere 0.10
- I do have only the exefs_patches and kip_patches w/ prod.keys
- Payload used: \fusee-primary.bin
- Current System date: 05/01/2018 06:09

**Previous working environment**
- Switch Firmware version => 5.0.1
- version of Atmosphere => None, I was on ReiNX_2.4
- version of sys-con => 0.5.2 - Atmosphere 0.10
- None

I can roll back to the previous version to help bug fixing and give more feedback.
Have happy holidays

**Comment by cathery** [comment]
sys-con works just fine on atmosphere 0.10.1 or firmware 9.1.0, make sure you've installed it correctly.

**Comment by mxswat** [comment]
Dear @cathery I just added more information about the bug.
Can you please confirm that It is only necessary to drag and drop the content of the latest release to make it working properly? I haven't touched the config files.

**Comment by cathery** [comment]
You need to reboot as well.

**Comment by mxswat** [comment]
I did the copy-paste of the files to the SD with my switch turned off using an SD to USB adapter.
Than reinserted my SD turned on it again and injected the payload because I have AutoRCM 
Does this boot count as a reboot? Or I need to actually reboot my switch now? 
Also, Reboot by the power menu or something else?

**Comment by mxswat** [comment]
Another detail, When I updated to 9.1.0 I did the switch joy-con controller update also.
And I did pair with my switch 2 more joy-cons a red and blue one.

**Comment by cathery** [comment]
It just means booting into Atmosphere. Anyway, since this is 0.10.1, make sure you have files located in `sdmc:/atmosphere/contents/690000000000000D/`. There should be a single exefs.nsp, as well as a flags folder with a boot2.flag file. This alone is enough to enable sys-con when booting into Atmosphere. On earlier versions of Atmosphere it would be located in `atmosphere/titles/...` instead.

**Comment by mxswat** [comment]
I can confirm  the files are in `/atmosphere/contents/690000000000000D/`
And the files are matching correctly.
Also, I noticed that when I connect the 360 unofficial controller it vibrate one time the light goes on but then it goes off

**Comment by cathery** [comment]
Can you send me the log located at `sdmc:/config/sys-con/log.txt`?

**Comment by mxswat** [comment]
I'm seeing that the log last modified date is on 5\1\2018

[log.txt](https://github.com/cathery/sys-con/files/4003062/log.txt)

**Comment by cathery** [comment]
I'm not sure what's going on with the time. Logs show that your controllers successfully connect. And they disconnect only after 10 seconds to a minute - that's probably you disconnecting them. Is your SD card formatted as exFAT? It has random corruption issues, make sure you're using FAT32. I'm only asking because your log times are weird.

**Comment by mxswat** [comment]
My SD is formatted to FAT32. But there is some garbage on it like pieces of reinx, I can do a clean SD wipe if you wish.
I can format it again to FAT32 and do a clean Install of my Atmosphere

**Comment by cathery** [comment]
It sounds like you had some reinx files left in the titles folder. If you overwrote on it with your Atmosphere.

**Comment by mxswat** [comment]
Do you suggest to remove entirely the ReiNX folder?

**Comment by cathery** [comment]
For testing purposes, yes

**Comment by mxswat** [comment]
Also, I edited my previous comment about the system date.
I'll set it to my current timezone to help with debugging okay?

**Comment by cathery** [comment]
Remove the atmosphere folder completely, install the latest atmosphere release, and then install sys-con. Tell me if it works

**Comment by mxswat** [comment]
> Remove the atmosphere folder completely, install the latest atmosphere release, and then install sys-con. Tell me if it works

Also the sept folder?
It was there before I installed the atmosphere

**Comment by cathery** [comment]
Yes, remove atmosphere, sept and hbmenu.nro and reinstall them

**Comment by mxswat** [comment]
To recap, at this moment I'm installing this:
atmosphere-0.10.1-master-71b220a4+hbl-2.3+hbmenu-3.2.0.zip
from Atmosphere-NX/Atmosphere/releases/tag/0.10.1
fusee-primary.bin as Tegra payload

**Comment by cathery** [comment]
Correct

**Comment by mxswat** [comment]
Current and previous state of my files in the SDcard using windows cmd ls command

https://pastebin.com/dwAzyXcM

I'm injecting the payload now

**Comment by mxswat** [comment]
Additional info I do not have the cartridge reader working in my switch after the 9.1.0 update and I'm not fixing it because I'm not using it

**Comment by mxswat** [comment]
Sadly it is still not detecting both my controllers they are still connected to the USB but no sign of life
Any idea?

**Comment by cathery** [comment]
No clue. Your logs indicate that sys-con is enabled and controllers get connected without any issue.

**Comment by cathery** [comment]
Unless... that's your logs from when you were running ReiNX, in which case sys-con is not enabled at all.

**Comment by mxswat** [comment]
I'm gonna check if there are any logs

**Comment by mxswat** [comment]
[log.txt](https://github.com/cathery/sys-con/files/4003153/log.txt)
I plugged the Controllers and no signal of life except the brief vibration and light going on
I tried to plug then in and out a few times and the switch refuses to see them as PRO controllers
Then I left the controllers in the dock for some time and still no sign of life
I'll try to update my system time and date to help us understand the logs

**Comment by cathery** [comment]
Your recent logs show that no controllers are being connected.

**Comment by mxswat** [comment]
This is super weird, any idea?

**Comment by mxswat** [comment]
Okay so Date updated to 18:55 current date,
Im gonna plug the controllers to my unofficial dock
and to an official dock

**Comment by mxswat** [comment]
With unofficial dock.
Inserted to USB 1 Xbox 360 unofficial controller no sign of life
Inserted to USB 2 Xbox 360 unofficial controller no sign of life
Inserted to USB 1 Xbox ONE wireless w/USB cable controller no sign of life
Inserted to USB 2 Xbox ONE wireless w/USB cable controller no sign of life

**Comment by mxswat** [comment]
With Offical dock.
Inserted to USB Xbox 360 unofficial controller IT WORKS!
Inserted to USB Xbox ONE wireless w/USB cable controller IT WORKS!

I assume that the atmosphere CFW does not handle properly the unofficial USB ports
For me, the bug is closed but there is a new interesting discussion to be done here or on atmosphere git hub page

I'm curious about using a USB hub with the official dock

**Comment by cathery** [comment]
Make sure your USB hub supports USB 2.0. I have a generic USB hub and it works just fine docked or undocked.

**Comment by mxswat** [comment]
[log.txt](https://github.com/cathery/sys-con/files/4003183/log.txt)
The log just in case.
What about supporting an unofficial dock? Should I report this to the Atmosphere team?

**Comment by cathery** [comment]
Don't expect unofficial products to work with anything. If you do decide to make a report, make sure to test that it doesn't work on Atmosphere and it works on ReiNX.

**Comment by mxswat** [comment]
> Don't expect unofficial products to work with anything. If you do decide to make a report, make sure to test that it doesn't work on Atmosphere and it works on ReiNX.

I'll wait for the next release of ReiNX and check.
Thanks a lot for your help and I hope this will help other users.
I wish you happy holidays
