### ISSUE TITLE
Hanging on reboot

### ISSUE THREAD

**Issue by Zeddeckia** [cathery/sys-con#12]
After I put the sysmodule onto my card and rebooted, my system began to hang on the Switch splash screen. Need some help? There isn't an error code or hard crash, either.

**Comment by cathery** [comment]
What is your version of switch and atmosphere?

**Comment by Zeddeckia** [comment]
9.0.1. and AtmOS 0.9.4

**Comment by Zeddeckia** [comment]
So the lastest, as far as I'm aware

**Comment by cathery** [comment]
I'll look into it

**Comment by Zeddeckia** [comment]
I appreciate it.

**Comment by JonJaded** [comment]
You're likely out of memory. When I was installing this I had sys-dvr activated and forgot to disable it.

Other high memory sys modules like sys-ftpd or like emuiibo can cause initialization hangs as well.

**Comment by cathery** [comment]
Yeah, i'm getting the same issue. It runs out of memory on switch FW 9.0.1, and when i allocate a smaller heap size, it doesn't have enough memory to run multiple controllers.

**Comment by Zeddeckia** [comment]
Ahh, alrighty. Thanks for the helo.

**Comment by Zeddeckia** [comment]
I assume there's no real way to remedy it either.

**Comment by cathery** [comment]
For now you could either downgrade to 8.0.1 or wait for atmosphere 0.10.0, it'll take me some time to figure out how to trim that memory down

**Comment by Zeddeckia** [comment]
I'll just have to wait.

**Comment by cathery** [comment]
I've uploaded a built that aims to reduce memory usage, can you tell me if it works? How many controllers can be connected at once?
https://files.catbox.moe/03zol5.rar

**Comment by Zeddeckia** [comment]
So can wireless controllers be hooked up via a USB? If so, then no, nothing's happening. If not, I'll invest in getting a completely wired controller for it.

**Comment by Zeddeckia** [comment]
I'm using an Xbox One first generation controller. I do have Dualshock 3 as well. I'm going to try those when I get home from work.

**Comment by cathery** [comment]
Wireless controllers need adapters. Adapters aren't yet supported, but theoretically possible. Hold on from investing, you might regret it.

**Comment by cathery** [comment]
Oh and use the latest release instead, it should be more stable

**Comment by Zeddeckia** [comment]
Alright. I'll try that and get back to you. Thanks for the support.
