### ISSUE TITLE
sys-con not working in the online emulators 

### ISSUE THREAD

**Issue by parkerlreed** [cathery/sys-con#122]
**Description**

No input in the NES/SNES online emulators

**How to reproduce**
1. Enable sys-con
2. Load the emulator

**Environment**
- Your Switch Firmware version: 9.1.0
- Your version of Atmosphere: 0.10.1
- Your version of sys-con: 0.5.2

**Comment by parkerlreed** [comment]
And I just realized I'm an idiot. It was showing up as player two so it didn't have any control.

**Comment by cathery** [comment]
oof
