### ISSUE TITLE
Does not work on 9.1.0

### ISSUE THREAD

**Issue by failsafe42** [cathery/sys-con#123]
**Description**

**How to reproduce**
1. Have switch running 9.1.0
2. Attempt to use sys-con
3. Controller does not do anything

**Environment**
- Firmware 9.1.0
- Atmosphere 0.10.1
- sys-con 0.5.2

**Comment by cathery** [comment]
It works on 9.1.0. Make sure your controller is supported. Make sure your controller is plugged in. If it's a second generation Dualshock 4, see the third warning on the main page.

**Comment by failsafe42** [comment]
Not quite sure what happened, but after reinstalling it 3 times it works.
