### ISSUE TITLE
xbox360 controller made puyopuyo tetris go wrong, then crash.

### ISSUE THREAD

**Issue by samoer123** [cathery/sys-con#125]
**Description**
when u use joycon, no problem,but when u use xbox360 controller, puyopuyo tetris went wrong, then quit.

**How to reproduce**   can't reproduce.

**Environment**
- Your Switch Firmware version   9.0.1 
- Your version of Atmosphere   0.10.2
- Your version of sys-con   0.51
- If you have any other sysmodules enabled, list them here.

**Comment by cathery** [comment]
Sounds like this was another case of incorrect joystick values, as diagnosed in #91
