### ISSUE TITLE
Dualshock 4 v1 and v2 simultaneously 

### ISSUE THREAD

**Issue by KazukiMutou** [cathery/sys-con#126]
Hi,

I'm currently using sys-con and all's working so far, however I'm running into a bit of an issue. I own both a DS4 v1 and v2, and changing the value in config_global.ini simply swaps support for either version. Right now when I enable v2 support, the v2 works normally but the v1 just stays in charge mode. And vice versa.

Would it be possible to just support both v1 and v2 at the same time?

**Comment by cathery** [comment]
It's currently an option to toggle between one or the other for a reason. There is a workaround though. Without turning off your switch (using ftpd for example), change the config value to use the v1 version, then plug in your v1 dualshock. Then again without turning off your switch and unplugging your v1 dualshock, change the config value to use the v2 version and plug in your v2 dualshock. I think that should let you use both dualshocks simultaneously, in theory at least.

**Comment by KazukiMutou** [comment]
This workaround indeed works. Would there be any possibility to add some sort of automation to this? Like just swapping the flag automatically based on which DS4 version gets connected. Maybe add an additional config option to enable/disable this functionality. Or would it be somehow possible to listen to a button combination to swap this around?

**Comment by cathery** [comment]
If I'm not able to find a way to detect every HID device in the future, I'll make an option in the upcoming companion applet to let you pick which 2 controllers you want to be recognized.
