### ISSUE TITLE
Xbox One Controller not working

### ISSUE THREAD

**Issue by oakami** [cathery/sys-con#13]
Is there any setup needed? I connect my Xbox 1 controller to the dock with USB and it vibrates once, then nothing happens. Controller doesn't work and no controller is detected.

**Comment by cathery** [comment]
Have you tried the latest release v0.2.2? It aims to fix first generation Xbox One controllers

**Comment by oakami** [comment]
Ah sorry I had an outdated version downloaded. It works fine now.
