### ISSUE TITLE
2nd gen DS4 issues (global thing set to true)

### ISSUE THREAD

**Issue by dylxnsm1th** [cathery/sys-con#131]
**Description**
When using either of my two gen 2 DS4 controllers only the analogue sticks worn regardless of cable or USB port.

**How to reproduce**
1. Install latest sys-con
2. Attempt to connect DS4 gen 2
3. Only analogue sticks work

**Environment**
- Your Switch Firmware version: 8.1.0
- Your version of Atmosphere: 0.9.1
- Your version of sys-con: 0.5.2
- No other sysmodules

**Comment by cathery** [comment]
Just tested on switch FW 8.1.0, AMS 0.9.1 and sys-con 0.5.2 and my 2nd gen DS4 seems to work fine. That being said, your Atmosphere is out of date. The latest version is 0.10.2. You should update it for good measure. Also, is your DS4 genuine?

**Comment by dylxnsm1th** [comment]
DS4 is genuine yes. I’ll update now thanks.

**Comment by dylxnsm1th** [comment]
Just updated all is good thank you!
