### ISSUE TITLE
Input-lag all controllers

### ISSUE THREAD

**Issue by Xdelta107** [cathery/sys-con#134]
Switch ver 9.0.1|AMS 0.10.2|

When the sysmodule is installed, official nx controller and unofficial start input-lagging when playing games, the input lag occur even if no third party controller is connected to the switch and using Bluetooth Pro and joy controllers

**Comment by cathery** [comment]
Please use issue templates correctly. What is your version of sys-con? Do you have any other sysmodules running? Does this happen when sys-con is disabled?

**Comment by FoxPlayer1889** [comment]
Version is the latest one, also it happens even if I have no sys module
expect syscon,

Il sab 25 gen 2020, 14:37 cathery <notifications@github.com> ha scritto:

**Comment by cathery** [comment]
Does this happen when you have NO sysmodules enabled?

**Comment by FoxPlayer1889** [comment]
Only with this sys module happen

Il sab 25 gen 2020, 14:39 cathery <notifications@github.com> ha scritto:

**Comment by cathery** [comment]
Okay. Does the lag happen when playing all games? Does the lag happen when you're in the home menu? Does the lag happen as soon as you start the switch? How often does the lag happen? How long does the lag last? How many controllers do you have connected at the moment of lag?

**Comment by FoxPlayer1889** [comment]
On the menu the lag is not present, only when starting the game,
I tried mk8dx, smash, cuphead, Yoshi for the moment

Il sab 25 gen 2020, 14:46 cathery <notifications@github.com> ha scritto:

**Comment by FoxPlayer1889** [comment]
1  third party controller connected and 2 pro controller

Il sab 25 gen 2020, 14:48 MarioCollector889 <lucapani741@gmail.com> ha
scritto:

**Comment by cathery** [comment]
I can't say I have ever experienced input lag on latest sys-con version but if I'll keep this open in case someone else has this problem.
