### ISSUE TITLE
USB Controller converter dongle as a pass through for a zero delay encoder

### ISSUE THREAD

**Issue by Unsteadycarrot** [cathery/sys-con#135]
I'm trying all sorts of methods to use my existing USB zero delay encoder with my nintendo switch, i know this program doesn't directly detect the USB zero delay encoder board (yet) but i thought maybe i could use a wired dongle as a passthrough.

[This is the one i bought](https://www.ebay.co.uk/itm/For-PS4-PS3-Xbox-One-360-Controller-Arcade-Stick-Adapter-for-Nintendo-Switch/192528252878?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649) (cheapest to try)

My encoder board controls are all set up to mimic a Ps2/Ps3 controller and i can switch between digital and analog controls using the mode button on the side of the cabinet.

running the diagnostics tool something showed up (without the dongle nothing would get detected which is probably due to it being a generic device)

![2020012313373700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/59772361/73142153-74a3b280-4083-11ea-8d82-9c734a7cc1ac.jpg)

Can anything be done? 
Thank you so much for your efforts with this tool so far, if this problem is completely unfix-able then i'll have to accept defeat.

* side note to explain what i need this for, i built up arcade cabinet that has a Ps2/wii U (using hid to vpad) and Odroid XU4 inside and the controls all play nicely with each other via usb and the switch is the only console it wont work with and there's some pretty cool games on their that would translate nicely to an arcade experience.

**Comment by cathery** [comment]
The fact that nothing shows up without the dongle is a little bit worrying. It should show ALL connected USB devices. The device in your screenshot is a Nintendo controller, and I would hope it doesn't need any modifications to work.
I have a knockoff controller that completely mimics the DS3 controller and it works with the sysmodule. The most important part that sys-con looks for is matching Vendor and Product IDs. For reference, that would be VID: `0x54c` (Sony) and PID: `0x268` (Dualshock 3).

**Comment by Unsteadycarrot** [comment]
After you mentioned that not showing up at all was worrying, i then had a similar problem connecting this board to my odroid xu4 and i have now found out that that usb b port on the encoder board just isnt working. 

So i got a splitter for the usb section that is working and the diagnostics tool detects it (hurrah) but it only functions when i use the controller converter i bought. So at least i am getting somewhere, is there anything else i need to know when it comes to being able to switch between left analog stick and d-pad? for some reason the "mode" button on my encoder board just functions as the switch home button.

other than that, i got some kind of functionality i can work with from here as now i can probably start to mess with the configs

**Comment by cathery** [comment]
There is an option in the config files for each controller to swap the d-pad and left stick around. I added this solely because some people had their fighting sticks recognized as d-pad buttons. I assume the "mode" button you're talking about would be the PS button on a dualshock controller, which I configured to emulate the home button.

**Comment by Unsteadycarrot** [comment]
excellent, i changed the setting on the controller converter from NS to PC and now the mode button functions as both the switch home button AND it changes between digital and analog. Thank you very much for your support, i now have exactly what i wanted using both a cheap dongle and sys-con.

I'll close this up now and share this info among certain arcade groups.
