### ISSUE TITLE
While DualShock 3 is connected turning off Switch or unplugging controller results in PS3 turning on

### ISSUE THREAD

**Issue by Dantenerosas** [cathery/sys-con#14]
Latest version 0.2.3 hotfix. FW 9.0.1, Atmos 0.9.4 vanilla. Tried this several times so I'm pretty sure it's not just random thing. 

Edit: Seems like something like this happens while console is turned off in dock and controller is plugged into it. Just now PS3 has been turned on by itself and player indicator on controller is lit (like someone pressed PS button to turn on console)

Edit 2: Nvm, I'm a dum-dum, forgot that this is default behavior for DS3 that is paired with a console. Haven't connected DS3 to anything but PS3 since I've bought PS4. Tho would be nice if this behavior could be circumvented somehow.

**Comment by deadair3210** [comment]
The only way to stop this would be to reassign the controllers home console, which would then make it refuse to connect to the original console until paired again

**Comment by Dantenerosas** [comment]
Yes, after remembering how controller behaves with PC I've gathered as much and I've already done this with one of my controllers aka replaced stored bluetooth address with zeros
