### ISSUE TITLE
Double Swapping key mapping, lost inputs ?

### ISSUE THREAD

**Issue by oocyberkevinoo** [cathery/sys-con#140]
When you ask to change the key mapping two times, ti just make disappear the key behind it.
I take for example my home made arcade controller : 
I have to swap B with Y to place B at the correct place, but after that, I have to move Y to his correct place, and it make it just disappear from all the mapping.

key_FACE_DOWN = FACE_LEFT
key_FACE_LEFT = FACE_RIGHT

all updated, no other sysmodule

**Comment by cathery** [comment]
Changed how it works: https://github.com/cathery/sys-con/releases/tag/v0.6.1
