### ISSUE TITLE
Console hangs up when I connect it to the dock with a xbox 360 wireless adapter connected

### ISSUE THREAD

**Issue by kiwanowski** [cathery/sys-con#141]
**Description**
When I take a console in sleep mode and connect it to my dock that has a xbox 360 wireless adapter connected - the adapter starts flashing. If I try to wake up the console while the adapter flashes - the console hangs up on a black screen and I have to reboot it. When I wait until the adapter stops flashing, the console wakes up normally.

**Environment**
- switch fw: 9.1.0
- atmosphere: 0.10.2
- sys-con: 0.5.3
- sys-clk enabled

**Comment by kcchong18** [comment]
try sys-con 0.5.1

**Comment by cathery** [comment]
Discussion on this is continued in #155
