### ISSUE TITLE
Xbox one controller keeps vibrating

### ISSUE THREAD

**Issue by cutecat13** [cathery/sys-con#142]
**Description**
When I connect my xbox one controller to my switch undocked (i don't own a dock) the controller doesn't light up and when I press the xbox button it keeps vibrating and doesn't work.

**Environment**
- switch firmware: 9.1.0 
- atmosphere: 0.10.2
- sys-con: 0.5.3 (i have tried some older versions too but no luck)

**Comment by cathery** [comment]
Try a different cable? The most important part of having a connected controller undocked is that you use an OTG cable. If you're using an adapter, it must be OTG as well.

**Comment by cutecat13** [comment]
Yeah i think i haven't been using an otg adapter. Thank You!
