### ISSUE TITLE
controller shows in screen but not working

### ISSUE THREAD

**Issue by Byrdman321** [cathery/sys-con#143]
I am on atmosphere 10.2 and fw 9.1.0. sys con 0.5.3 when I plug in my xbox one controller it shows detected in left corner but I get no response from it , does not control anything

**Comment by Byrdman321** [comment]
UPDATE: if you use the original Nintendo dock I guess the usb ports on the side dont work with sys con I have to plug the 3rd party controller in the usb port in the back behind the flap door on the dock for it to work. works fine without dock and using OTG adapter too.

**Comment by cathery** [comment]
sys-con does not have any control over which USB port you plug your controller in. Make sure your dock is working correctly.
