### ISSUE TITLE
My Xbox 360 Controller for Windows is not working

### ISSUE THREAD

**Issue by dusy118** [cathery/sys-con#144]
my switch sys is 8.1,and atmosphere 0.9.2
my Xbox 360 Controller for Windows
![2020022120532500-CCFA659F4857F96DDA29AFEDB2E166E6](https://user-images.githubusercontent.com/61319485/75039200-1be4ff80-54f3-11ea-95c2-fb93f2c9bd8b.jpg)
![20200221214327](https://user-images.githubusercontent.com/61319485/75039253-3dde8200-54f3-11ea-9a6d-b47221efa3a1.jpg)
![20200221214628](https://user-images.githubusercontent.com/61319485/75039443-afb6cb80-54f3-11ea-9a4a-c5fbb4fd0992.jpg)
It is not working.
Thank you for helping :)

**Comment by Alistair1231** [comment]
Just as a note, with the original it's working fine for me.
![image](https://user-images.githubusercontent.com/26165288/75610785-a392c580-5b14-11ea-8140-f89e92b38c75.png)
![image](https://user-images.githubusercontent.com/26165288/75610786-a55c8900-5b14-11ea-93b8-9a7ae8968c92.png)

**Comment by cathery** [comment]
Your third party controller does not follow the XInput protocol and thus will not be recognized as a valid Xbox 360 controller.

**Comment by EISENB** [comment]
i have a xbox360 wired with usb adapter  and sxos , ans it doesnt work , i spend two day trying all version alle devices are update.
