### ISSUE TITLE
Not working with any controller 

### ISSUE THREAD

**Issue by mihadoffical** [cathery/sys-con#145]
Hey, I can’t seem to get this to work at all :/

Fw:9.1.0 
Cfw: tried with both atmsphr and kosmos, both fully up to date
Controller: have tried a ps4 gen1 as well as a xbox1 controller

I have used multiple cords in all 3 slots of the dock, on both controllers several times. 
ps4 controller turns orange as if it was charging for a second and then turns off, nothing on the console.

Xbox controller doesn’t absolutely nothing on both console and controller itself.

I have gone through all the config files to see if I needed to change anything, but nothing really seems to be of interest.
When booted in kosmos I have the ability to turn it on or off in toolbox But it doesn’t change anything. 

I have a lot of stuff on my sd card that I’m not too keen on getting rid of, but my joy con stick drift is to the point where games are pretty much unplayable. Should I just bite the bullet and reset/start from scratch? Or have I missed something in my troubleshooting? Any help would be appreciated :)

**Comment by cathery** [comment]
sys-con still works on FW 9.1.0 (or 9.2.0 for that matter), and latest Kosmos includes sys-con automatically. Go to Kosmos Toolbox and make sure sys-con is on. You can tell if you have a gen1 dualshock 4 if it doesn't have a light bar on the touch pad, and gen1 dualshock 4 should work by default. Xbox one controller should at least show up as a controller icon in your home menu. You could also have issues if you're not using the official dock. You could also have issues if the USB cable for your controller can't transmit data (aka used only to charge batteries).

**Comment by mihadoffical** [comment]
@cathery Hey, thanks for the quick reply, I do have official dock and I’ve attempted to use multiple usb cords, so I’m not entirely sure what the exact problem was. I’ve decided to just go ahead and format and reinstall cfw, hopefully that fixes it, if not, I’ll probably just move on. Thank you again!
