### ISSUE TITLE
Only recognizes 2 controllers at the same time

### ISSUE THREAD

**Issue by venom19910** [cathery/sys-con#147]
When I was using atmosphere 0.9.4, and syscon 5.1, I was able to play with 3 controllers (2 ps4 and 1 ps3) at the same time. After I update to atmosphere 0.10.3 and the latest version on syscon, the switch only recognizes 2 controllers at the same time

**Environment**
- Your Switch Firmware version 9.2.0
- Your version of Atmosphere 10.3
- Your version of sys-con 5.3
- I have not other sysmodules

**Comment by cathery** [comment]
I have recognized this problem and it will be fixed in the next release. I will keep this issue open for now so others can see it

**Comment by venom19910** [comment]
Thank u for your work!!

**Comment by fallkord** [comment]
Hi. I have similary problem but with first and second generation of ps4 controls (first come with my consola and the second bought months algo)

I change the config/sus-con/config_global.ini value to “true”   Now the system only admit the 2nd generation control. How can i Fix This and recognize both controls?

(Sorry if this is no the Chanel to consult this and my bad english) 

Thanks you for you colaborations

**Comment by cathery** [comment]
https://github.com/cathery/sys-con/releases/tag/v0.6.0
