### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Rotockter** [cathery/sys-con#149]
I have installed today a fresh version of Kosmos with Atmoshphere over the sdsetup package, including sys-con 0.5.3 and it just nothing happens then plug in my ps4 controller, into the docking station, with second gernation turned on/off, or my ps3 controller or my xbox 360 controller.

I booted with hekate into emuMMC firmware 9.2.0

**Comment by cathery** [comment]
Open Kosmos Toolbox and go to Background services, does it say that sys-con is enabled?

**Comment by Rotockter** [comment]
I did not know that this "sys-" things could be enabled/disabled in this toolbox.
It was turned off.
Now its works. My Ps4 controller works finaly (>w<) b 
Many Many Thanks.  
I bought you 2 Ko-Fi's worth of thanks.

I bought a used switch. The left joycon has a strong random drifting upward. So using other a controller, i dont need immediately repair the analog stick, now (^w^)

Would be cool if someone could include that in guides, because no where i saw this mentioned that this "sys-" things can be managed through homebrew.

**Comment by cathery** [comment]
I'm happy that it worked for you, I also agree that the guides should be updated
