### ISSUE TITLE
Xbone Controller Drift

### ISSUE THREAD

**Issue by Sumpftier** [cathery/sys-con#15]
Still there with the newest update

**Comment by Sumpftier** [comment]
I think that a bigger deadzone is needed

**Comment by cathery** [comment]
I'm writing a config file to let you modify the deadzone

**Comment by Sumpftier** [comment]
thx!

**Comment by cathery** [comment]
You can now modify stick deadzone in the config files of [0.3.0](https://github.com/cathery/sys-con/releases/tag/v0.3.0)
