### ISSUE TITLE
Problems with diferent ps4 controller generation

### ISSUE THREAD

**Issue by fallkord** [cathery/sys-con#150]
Hi

First thanks you for Your work and dedication. :)
I have a little problem. I have 2 ps4 controllers of diferent generation. I cant play with both controllers. How Will be fixed?

I dont have problems playing with one of them. 
And i try change config/sus-con/config_global.ini value to “true”

Pd: sorry my bad english
**Environment**
- Your Switch Firmware version 9.2.0
- Your version of Atmosphere 0.10.4
- Your version of sys-con last

**Comment by cathery** [comment]
At the moment the only possible way to play with both DS4 controllers is by plugging in one controller, changing the setting in the config file (without turning off the console or unplugging the first controller) and plugging in the second controller.

**Comment by cathery** [comment]
It can now detect both generations at the same time: https://github.com/cathery/sys-con/releases/tag/v0.6.1
