### ISSUE TITLE
Sys-Con Won't Work - Tried Everything

### ISSUE THREAD

**Issue by leobeloto** [cathery/sys-con#151]
Hello People! first of all thank you soo much for this sys-con to play the games with other controllers, but i have a little problem.

I'm using SX OX and i tried everything, i searched on how to install from this "issue" forum and youtube tutorials, but it still won't work! and i only have an ps4 2nd generation controller and a wii u pro controller ( i know that wii u pro controller does not have the support, but i tried anyway ).

can someone help me?

My Files from sys-con/Sd Card:

SXOS\title\690000000000000D
config on root of sd card.

ps: i already rebooted the console twice!

- Switch Firmsware version 9.1.0
- SX OS Version 2.93
- Sys-con version 0.53

Thank you for your time and answer!

Have a nive quarantine day, Kappa

**Comment by cathery** [comment]
Only Atmosphere is actively supported for sys-con. If it continues to not work on Atmosphere, make a new issue. Make sure it's installed properly. Make sure you enable the setting in global config for 2nd generation dualshock 4 controllers.
