### ISSUE TITLE
Pls pick up the development again this work is awesome and love see bluetooth workin!

### ISSUE THREAD

**Issue by TraeF1337** [cathery/sys-con#152]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cathery** [comment]
sys-con is being actively worked on: https://github.com/cathery/sys-con/commits/libstrato-rewrite
bluetooth is also being slowly reversed: https://github.com/cathery/nx-btdrv
This isn't even an issue so i'll just close this
