### ISSUE TITLE
DS4 2nd gen not working.

### ISSUE THREAD

**Issue by RageMouse** [cathery/sys-con#154]
**Description**
I'm using SXOS, and I've followed the instructions. Extracted to files to my root sd and put the contents folder inside of my sxos folder. I plug in my controller and it blinks once, and then does nothing. My other controller the light will be on but it doesn't do anything. I have changed the 'false' to 'true' in global settings.

**Environment**
- Firmware v9.1.0
- SXOS Beta v2.9.4
- v0.5.3

**Comment by cathery** [comment]
Only Atmosphere is actively supported for sys-con. Boot into atmosphere and repeat the above steps. If this still doesn't work, please make a new issue.
