### ISSUE TITLE
Xbox 360 Charge and Play Support

### ISSUE THREAD

**Issue by GeorgeCalderoESP** [cathery/sys-con#16]
Hello.

Thanks for that file.

Can you make a file for Reinx? Or is it loadable from Renx?

Thanks.

**Comment by cathery** [comment]
Try copying the contents of the zip file except with `ReiNX/` folder instead of `atmosphere/`

**Comment by GeorgeCalderoESP** [comment]
> Try copying the contents of the zip file except with `ReiNX/` folder instead of `atmosphere/`

I use XBOX 360 Play and charge kit, using USB Port.

NSW doesnt detect any controller.

I tried with AMS and Reinx.

Any Help please? Thanks.

**Comment by cathery** [comment]
Can you try this version? https://files.catbox.moe/pwrpyl.rar

**Comment by GeorgeCalderoESP** [comment]
It doesnt work.

Can you tell me if xbox360 play and charge is compatible?

Thanks,

**Comment by cathery** [comment]
No, not right now

**Comment by mzino** [comment]
IIRC the Play&Charge kit only passes current to power up the controller, but no data connection is involved, so it wouldn't work on PC either. Please correct me if I'm wrong.

**Comment by GeorgeCalderoESP** [comment]
Yeah !! You are right, it only passes current, no data.

I use a wireless receiver to play with the controller on PC.

I will wait until wireless receiver works on your sys-con.

Thanks !

**Comment by cathery** [comment]
Based on the information I've seen, Charge and Play doesn't send any data through the USB, so it's not possible to implement it. However, wireless receiver has been implemented and will be up in the next release (see #11 )
