### ISSUE TITLE
Disable certain keys for controllers

### ISSUE THREAD

**Issue by fullmetal1** [cathery/sys-con#161]
So the reason why I'm making this feature request is because my brother can't stop hitting the capture button on any controller he uses, so I want to disable it for his controller. Currently I am swapping the SYNC and TOUCHPAD keys for the controller type. In a future release could you have a setting to disable a key altogether, either for a specific controller type, or globally? I suppose this feature is only needed if there's a use case for disabling multiple keys, or if the TOUCHPAD key ever starts working (in fact I haven't tested that it is, the touchscreen isn't used in the games we play together.)

**Comment by fullmetal1** [comment]
Horizon Firmware version 10 supports remapping keys but I'm not sure how adept this is or if it can be used as a solution to this feature request. When I update my switch I'll test it out and close this feature request if it works.

**Comment by cathery** [comment]
Current button remapping for sys-con is pretty lacking, i.e. only allows you to swap keys around and doesn't support multimapping or unmapping. I'll update it eventually

**Comment by cathery** [comment]
https://github.com/cathery/sys-con/releases/tag/v0.6.1
