### ISSUE TITLE
Xbox360 controller does not connect and does not recognize you

### ISSUE THREAD

**Issue by luisito1983** [cathery/sys-con#163]
my official xbox360 controller does not connect and does not recognize you, tested with two xbox360 controllers and no response.
Why does he not recognize them?

**Comment by Conan179** [comment]
With or without the xbox360 controller adapter?

**Comment by luisito1983** [comment]
With the connected, it does not recognize you and does not appear, the lights of the ball remain blinking


Enviado desde Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by cathery** [comment]
Make sure you're using a USB cable that can transmit data. Make sure sys-con is enabled. I don't understand what you're saying
