### ISSUE TITLE
Keybinding on official controllers 

### ISSUE THREAD

**Issue by michalboss123** [cathery/sys-con#165]
Since hid-mitm is not supported , was wondering if it was possible to use the keybinding options in syscon on Nintendo switch supported controller. Been trying to rebind swap dpad and joystick , so I could use fightstick on smash Bros Ultimate but no luck .plz would you add keybinding options for Nintendo supported controllers ?

**Comment by cathery** [comment]
You can now change button mapping on official controllers with FW 10.0.0, so there's no reason for sys-con to add that feature. Besides, you'd need something to mitm the hid service (which is exactly what hid-mitm does) to modify official controllers. sys-con doesn't do any of that. And last I saw hid-mitm has been updated to work with latest Atmosphere, just no release yet. You could try building that yourself if you're interested.

**Comment by michalboss123** [comment]
Now checked out the mapping settings and they kinda meh , you cannot use 3rd party switch controllers and cannot rebind directions of joysticks . It ok if you don't want to add it into syscon
