### ISSUE TITLE
Sys-con causes Super Mario Odyssey to softlock console

### ISSUE THREAD

**Issue by joshuajaharwood** [cathery/sys-con#168]
**Description**
Having sys-con enabled causes the Action Guide in Super Mario Odyssey to softlock the entire console, forcing a hard reboot.

**How to reproduce**
There are multiple methods to reproduce this.

**[1] From menu (easiest)**
1. Select 'Action Guide' from the main menu.

**[2] In-game**
1. Boot the game
2. Load in to 'Showdown on the Inverted Pyramid'.
3. Cross the moving bridge
4. Speak to the sombrero-wearing skull guy below the inverted pyramid. Select 'Show me!'.

These will result in the Action Guide loading, which will then softlock the console.

**Environment**
Console is undocked, with both joycons attached by rail.

- HOS 10.0.0, though this also occured on 9.1.0.
- Kosmos v15.6.
  - Atmosphere 0.11.1
  - sys-con 0.6.0
- Sysmodules enabled: sys-ftpd-light, Tesla, ldn_mitm
- Sysmodules disabled: sys-con (fixes the issue)

**Save file**
You can load this using Checkpoint.
[20200420-210812.zip](https://github.com/cathery/sys-con/files/4505958/20200420-210812.zip)

**References**
https://github.com/Atmosphere-NX/Atmosphere/issues/775

**Comment by cathery** [comment]
I can confirm that the softlock occurs with the following 4 sysmodules enabled in Kosmos v15.6. I can't confirm that sys-con causes the issues because disabling any one of those sysmodules fixes the issue (at least for me). Does this softlock still occur when you disable any other sysmodule?

**Comment by cathery** [comment]
I can experience action guide softlocks with many combinations of sysmodules enabled that don't include sys-con. So, for now, this isn't a sys-con issue. It's something bigger.
