### ISSUE TITLE
sys-con crashes hbmenu on HOS 10.0.0+

### ISSUE THREAD

**Issue by kingafro000** [cathery/sys-con#169]
First off I want to say how much I appreciate the work you've been doing. there's only been one bug I've encountered so far, which is that it seems to crash the hbmenu when enabled. I should also mention that this has been happening while not docked and no controllers connected. I only have sys-ftpd-light running, so I don't believe that too many sysmodules is the issue.

**How to reproduce**
1. enable sys-con
2. open hbmenu via title
3. get atmosphere crash screen.

**Environment**
- Horizon 10.0.1
-  AMS 11.1 (I'm using the latest Kosmos)
- Latest sys-con
- sys-ftpd-light
- hbmenu v3.3.0

**Comment by cathery** [comment]
What is the error code? Does it still happen if you have sys-con or sys-ftpd-light disabled?

**Comment by kingafro000** [comment]
The Error code is 2345-0038, and it says the program is 0100000000010000 if that is relevant.
I just tested and it only crashes if the two are running, disabling either stops the crashes. I should also mention that I have the tesla menu running if that could also be contributing to it.

**Comment by cathery** [comment]
The crash error comes from libnx, specifically `LibnxError_InitFail_Time`. That seems to happen a lot on HOS 10.0.0+ because processes run out of time sessions and decide to abort. Only solution right now would be to disable other sysmodules that use time (sys-con, sys-ftpd-light, emuiibo, maybe some others)

**Comment by kingafro000** [comment]
Yea that's definitely the problem, disabling either tesla or the aforementioned sysmodules fixes it. Thanks for your help!

**Comment by cathery** [comment]
by the way, i'm running sys-con + sys-ftpd-light + tesla with no issues. Make sure Tesla/nx-ovlloader is updated as i remember it removing the need for time handles
