### ISSUE TITLE
0.2.3 do not work, 0.2.2 work

### ISSUE THREAD

**Issue by halop** [cathery/sys-con#17]
Hi, version 0.2.2 work with my xbox one controllers, version 0.2.3 does not work any more.
It only vibrates once, then nothing happens.

**Comment by cathery** [comment]
What is your version of Switch and Atmosphere?

**Comment by halop** [comment]
Switch 9.0.1
Atmosphere 0.9.4 with Emunand (Kosmos 14.2)

**Comment by vassall89** [comment]
Doesn't work for me I'm using an xbox one s controller , i already renamed the nsp to exefs doing this when i plug the USB cable the console recognized that a usb controller was plugged but the controller just vibrates and nothing happened no button press is detected , my console is running 9.0.1 and atmosphere 0.9.4

**Comment by halop** [comment]
it works, thanks
