### ISSUE TITLE
Is it possible to support Ring-Con?

### ISSUE THREAD

**Issue by daizong** [cathery/sys-con#171]
reference: https://github.com/cathery/sys-con/issues/9
We can't modify motion sensor values on the switch.

Is it possible that just activate another key not remap motion.
like the script of titan two: https://www.controllerbend.com/uploads/1/3/0/5/130564419/joycon_botw_runless.gpc
for example:
squeeze Ringcon to activate Y button.

And switch os 10.0+ support to remap generic keys.

**Comment by cathery** [comment]
Ring-Con is already supported by the switch
