### ISSUE TITLE
DS4/PS4 Controller won't connect

### ISSUE THREAD

**Issue by Pysis868** [cathery/sys-con#172]
Could be an off brand 'Doubleshock' variant...
Is that close enough to support?

Plugging in with USB cable makes it light up yellow.
I think you can see the light through a small strip along the top of the touch pad.
Pressing PS button blinks blue searching for console, then goes back to yellow after a bit.
Tried pressing sync button.  Just makes the controller turn off.

I got this USB cable to work with my Xbox One controllers, they just have disconnection issues with the delicately plugged in cable and take a minute or two to reconnect every time, at least maybe on an older sys-con version (0.3??).

Is there an exact usage guide for each controller or in general?  Probably not since those work.  I can visualize it in the controller applet which is best for debugging.  Don't need to change grip/order or find, except setting it as the first player slot once every HOS boot.

Official dock.
Using side USB ports.

HOS 10.0.1
AMS 0.12.0
sys-con 0.6.1? from today
Other sysmodules loaded.

**Comment by cathery** [comment]
In latest version, it's enough to just have the sysmodule enabled. Plug the controller in, it might light yellow for a bit and then change the LED color. That means the controller connected. If it never changes the color, something isn't working right. You're not sure if your dualshock controller is genuine - sys-con currently only handles the exact Sony vendor and product IDs, and it won't detect anything other than that.
