### ISSUE TITLE
8 Bitdo adapter doesn't work with DS4 pad [Both version] (and propably any other pad)

### ISSUE THREAD

**Issue by etharos** [cathery/sys-con#173]
FW 9.0.1 / Kosmos 15.6 /  Sys-con 0.6.1

With sys-con is enabled, when pair DS4 controller to 8bitdo -> cotroller paired (blue led lighting), but cotroller doesn't work.  Switch doesn't see pad, any button doesn't work. I've checked both version pad [V1 and V2].

Propably 8bitdo used PC mode when sys-con is enabled, adapter goes to xinput mode. 

Add this adapter to somekind blacklist for sys-con module, propably will solve this problem.

**Comment by etharos** [comment]
Update Firmware 8bitdo from 1.26 to 1.30 resolved problem - topic to close.

**Comment by cathery** [comment]
sick
