### ISSUE TITLE
Sx os issues

### ISSUE THREAD

**Issue by hyoids** [cathery/sys-con#176]
On 10.0.1 and sx os 2.9.5.
Sys-con doesnt work, i tried to delete all files and make new ones but i doesnt work. I try xbox 360 and xbox one controller but nothing happens. On my switch settings made wired controller on. Is there anything that i can do?

**Comment by Conan179** [comment]
its never run on sx os.
SX OS does not allow system modules.

**Comment by hyoids** [comment]
I used it on sx os properly. Besides it doesnt say 'not compatible with sx os'

**Comment by cathery** [comment]
Support for SX OS (or any other CFW) is purely accidental. All releases of sys-con have only been tested on Atmosphere.
