### ISSUE TITLE
Release 0.2.3's NSP name is wrong

### ISSUE THREAD

**Issue by UnicornsOnLSD** [cathery/sys-con#18]
The name of the NSP in `sdmc:/atmosphere/titles/690000000000000D` is sys-con.nsp when it should be exefs.nsp. This is why 0.2.3 doesn't work (#17). I'd recommend you release 0.2.3.1 so that people are notified about the fix.

**Comment by Gullib** [comment]
Do you think that renaming it will fix the thing?
Lie from my pc

**Comment by cathery** [comment]
thank you! i can't believe i didn't notice this

**Comment by cathery** [comment]
oh man

**Comment by cathery** [comment]
Released [0.2.3.1](https://github.com/cathery/sys-con/releases/tag/v0.2.3.1)
