### ISSUE TITLE
i am on SXOS , i did the replacement correctly , but noone of the xbox 360 wired or the dual shok ps4 wirreless is working.

### ISSUE THREAD

**Issue by EISENB** [cathery/sys-con#184]
**Description**

**How to reproduce**

**Environment**
- Your Switch Firmware version
- Your version of Atmosphere
- Your version of sys-con
- If you have any other sysmodules enabled, list them here.

**Comment by cathery** [comment]
SXOS is not supported. Wireless is not supported (right now).

**Comment by EISENB** [comment]
sorry not wirreless just bloothouth ps4

**Comment by Conan179** [comment]
bloothouth  IS wirreless!
There is no cable between the switch and the DS4

**Comment by EISENB** [comment]
Ahoo my guess. I mean wi-fi sorry my English is so bad. So will you make
the sxos working later?

**Comment by EISENB** [comment]
hi bro , the controllers are working like a charme , thnks for your job .
