### ISSUE TITLE
Support for Atmosphère 0.13.0

### ISSUE THREAD

**Issue by krouwndouwn** [cathery/sys-con#189]
**Is your feature request related to a problem? Please describe.**

Atmosphere - release notes:
- Please note: this is (unavoidably) a breaking change. System modules using atmosphere-libs will need to update to understand what firmware version they are running.

**Comment by Tardigrade-nx** [comment]
I confirm sys-con 0.6.2 causes a crash with Atmosphere 0.13.0

**Comment by cathery** [comment]
sys-con uses Atmosphere-libs, but it doesn't use it to check firmware version (as it's known to crash with every new firmware version). As such, it should be unaffected. If you have a crash, please send a crash report.

**Comment by gut5** [comment]
Can confirm, 0.6.2 works fine on AMS 0.13
