### ISSUE TITLE
0.2.3 Xbox one s controller

### ISSUE THREAD

**Issue by vassall89** [cathery/sys-con#19]
Doesn't work for me I'm using an xbox one s controller , i already renamed the nsp to exefs after doing this when i plug the USB cable the console recognized that a usb controller was plugged but the controller just vibrates and nothing happened no button press is detected , my console is running 9.0.1 and atmosphere 0.9.4

**Comment by z0oinks** [comment]
Try another USB cable. That was happening to me when my USB->microUSB was power only. You'll need one that supports data

**Comment by vassall89** [comment]
I update to 3.0 press the xbox controller and when it starts flashing plug the cable and it worked thank you
