### ISSUE TITLE
problema sólo en animal crossing

### ISSUE THREAD

**Issue by rubenabril** [cathery/sys-con#190]
**Description**
en animal crossing el jugador se mueve automáticamente hacia abajo e izquierda... ocurre desde la última actualización de sys con...
el resto de juegos no hay problema
estoy usando mando de xbox 360 con cable

**How to reproduce**

**Environment**
- 10.0.4
- Your version of Atmosphere 0.13.0
- Your version of sys-con (last)
- If you have any other sysmodules enabled, list them here.

**Comment by cathery** [comment]
please speak english
