### ISSUE TITLE
SX OS Support

### ISSUE THREAD

**Issue by AzukaChan** [cathery/sys-con#194]
Its a little bit disappointing to see there is no support for SXOS.

**Describe the solution you'd like**
1) sys-con.nro - Direct download to your console
Open the "sys-con app" and select which verison you would like to download (Atmosphere, Neutros, SXOS, etc)
Obviously this app would need to be made but from a developer point of view seems simple enough. 

**Describe alternatives you've considered**

2) Release a SXOS version in the HBAppStore/New Branch for SXOS users?
Having the app would be nice to avoid removing the SD Card from the console; however as an alternative maybe you could open an SXOS/developer branch of sys-con?

**Additional context**
sys-con 0.5.3 was working fine on SXOS; once the 0.6.0 update was released all controllers stopped working.

**Comment by cathery** [comment]
- SX OS (and any other CFW with no established standard) is a pain in the ass to support
- It never officially supported or advertised support for custom sysmodules and I don't believe there are any dev tools for it
- It uses practices I don't endorse or support (it illegally uses and redistributes Atmosphere code without disclosing source or including the license/copyright notice)

If someone is willing to maintain compatibility for SX OS, they can always create a fork of the repository and do it themselves.

**Comment by AzukaChan** [comment]
@cathery 
Well considering how easy it was to mine working; I think I might be that person.
For anyone using SXOS and wanting to get this working, here are the steps required:

1. Download "sys-con" from the HBAppStore.
2. Using SXInstaller, browse your SDCard and find the `"SD:\atmosphere\contents\690000000000000D"` folder created by sys-con. 
3. Copy the folder `"690000000000000D"` and place it in `"SD:\sxos\titles\"`. 
4. Your finished directory should look like this: `"SD:\sxos\titles\690000000000000D"`

Will work on recompiling for SXOS users to avoid other people having a similar issue; thanks.
