### ISSUE TITLE
Controller not detected

### ISSUE THREAD

**Issue by nfjc** [cathery/sys-con#197]
When I try to use a controller with the dock the logo doesn't show up and no inputs are detected. I've tried both an xbox one controller and a ps4 one. I would love to have some help to fix this because the switch controls are terrible in my opinion.
Thanks in Advance.

**Comment by cathery** [comment]
Make sure the sysmodule is enabled. Make sure the switch is in the dock. Make sure your switch version is up to date. Make sure your Atmosphere version is up to date.

**Comment by nfjc** [comment]
How do you enable it? What's the latest switch version? I'm not using atmosphere.

**Comment by cathery** [comment]
This is an Atmosphere sysmodule, you must be in Atmosphere to use it. The latest switch version is 10.x.x something (should work without issues). After you downloaded the files and dropped them into your SD card, you can enable it by booting/rebooting into Atmosphere, or by enabling it manually in Hekate Toolbox (if you have it).

**Comment by nfjc** [comment]
So there's no way for it to work in sxos?

**Comment by cathery** [comment]
It may work, it may not. I am not responsible for this. SXOS never claimed to support custom sysmodules.

**Comment by nfjc** [comment]
would all my games/homebrews transfer over to atmosphere?

**Comment by cathery** [comment]
Sure.

**Comment by nfjc** [comment]
thanks.

**Comment by nfjc** [comment]
I got it to work in atmosphere but is there a way to invert a and b and x and y? it was the whole reason i wanted this

**Comment by cathery** [comment]
You can change the button mapping for each type of controller in sdmc:/config/sys-con/

**Comment by nfjc** [comment]
Im somehow stupid enough to attempt this but ended up making both the a and b keys do nothing on my cont. Can you help? I just want to swap a with b and x with y

**Comment by cathery** [comment]
There should an example in each config file. You'll want to add these lines in your config:
KEY_FACE_RIGHT = FACE_DOWN
KEY_FACE_DOWN = FACE_RIGHT
KEY_FACE_LEFT = FACE_UP
KEY_FACE_UP = FACE_LEFT

**Comment by nfjc** [comment]
Godsend thanks. Are there plans to port to sxos?

**Comment by cathery** [comment]
No

**Comment by nfjc** [comment]
dang thanks anyway.
