### ISSUE TITLE
Xbox 360 Wireless version with "Charge and Play" USB Cable

### ISSUE THREAD

**Issue by SageAlchemia** [cathery/sys-con#20]
Hello! First of all, you are fantastic! Thanks for your effort to bring us a wonderful modification!
I have a Xbox 360 controller, wireless edition, and when put together with the USB cable "Charge And Play" doesn't work. 
The Switch don't recognize it. 
I tested it in 0.2.2 and 0.2.3 Version.

Thanks for all!

**Comment by cathery** [comment]
Can you try this version and see if it works? https://files.catbox.moe/rdz1g3.rar

**Comment by theshah75** [comment]
tried it, didnt work :(

**Comment by SageAlchemia** [comment]
It does not work.
Tried and nothing. Before, with 0.2.3 or 0.2.2, it detected the battery charge, not now.
Still unable to detect control.

**Comment by mzino** [comment]
Play&Charge doesn't support data. See https://github.com/cathery/sys-con/issues/16

**Comment by cathery** [comment]
Can you launch this applet and send me a screenshot of the scanned controller? https://files.catbox.moe/re60qo.rar

**Comment by SageAlchemia** [comment]
![IMG_5519](https://user-images.githubusercontent.com/57470553/68439591-f1bb3c00-01a6-11ea-892b-616fa6ca2b04.JPG)
*With the USB "Charge & Play"


![IMG_5520](https://user-images.githubusercontent.com/57470553/68439623-0c8db080-01a7-11ea-9741-9506c3dff889.JPG)
*With the Wireless Oficial Dongle

Tested in 0.3.0

**Comment by gilest** [comment]
Can probably be closed since the controllers themselves have no USB data. Dongle support tracked by #11

**Comment by cathery** [comment]
Based on the information I've seen, Charge and Play doesn't send any data through the USB, so it's not possible to implement it. However, wireless receiver has been implemented and will be up in the next release (see #11 )
