### ISSUE TITLE
XBOX Elite Controller 2 doesn´t have any input

### ISSUE THREAD

**Issue by RicardoR12534** [cathery/sys-con#200]
So, I installed sys-con yesterday and the controller was working wonders. Today, after a reset to the console, the controller doesn't work again.
I have the wired Pro Controller option enabled. My controller has its software updated.  Tested every version from 5.3 and up, including some in another issue about this controller. Atmosphere 0.13.0, Hekate 5.3.2

**Comment by cathery** [comment]
Elite controllers are a very uncharted area for me. What do you mean by "reset to the console"? When you plug in the controller, does the controller icon show up? Can you press the xbox button on your controller so it starts blinking, and then plug the controller in?

**Comment by RicardoR12534** [comment]
Reset as in factory reset. The icon shows up, no input. I press the button, starts blinking, plug in the controller, icon appears, no input. Docked and undocked.

**Comment by cathery** [comment]
No clue, but try using the xbox accessories app for windows to update the software on your controller, even if it's up to date.

**Comment by RicardoR12534** [comment]
Aaaaand it works again. I'll keep you updated if it brakes again.

**Comment by cathery** [comment]
Maybe you forgot to include the config files?

**Comment by RicardoR12534** [comment]
The config folder? Copied everything in the zip. There was no difference between the files before and after testing atmosphere 0.12.0. The only thing I changed was the payload. Used the one included with 0.12 instead of the 0.13 one. Maybe a lucky mistake?

**Comment by RicardoR12534** [comment]
YESSSSSSSSSSS found the problem. If I connect the controller to any device via Bluetooth, it stops working on the switch. If i connect it to my PC via USB and then again to the switch it works again. A strange bug indeed.
