### ISSUE TITLE
When I connect ps4 controller as second controller, buttons don't work. I solved it when I pressed the joycon home button and the ds4 controller is already connected. It's awkward to do that, so I ask that they be resolved.

### ISSUE THREAD

**Issue by Rodry295** [cathery/sys-con#201]
**Description of the controller**
The description of your controller. Write down its intended usage, whether it supports USB, Bluetooth, motion controls, rumble, HD rumble, etc.
Before submitting the issue, make sure this controller is not already supported.

**Screenshot of the device**
1. Download this diagnostics applet https://files.catbox.moe/re60qo.rar
2. Run it from the homebrew menu.
3. Plug in the controller into the switch.
4. Press Y to scan and then take a screenshot.
5. Post the screenshot here and erase these steps.

**Additional context**
Add any other context about the controller request here.

**Comment by cathery** [comment]
Can't reproduce
