### ISSUE TITLE
Xbox One S controller - Detected but no input recognized

### ISSUE THREAD

**Issue by SteinsM4te** [cathery/sys-con#202]
I've set up sys-con on my Switch (Atmosphere 0.13.0 & FW 10.1.0). I plug the USB-B to Xbox One S controller and via USB-C OTG to the Nintendo Switch. The console detects the controller (see picture 1) but any input is not recognized (buttons, sticks, anything).
I've tried multiple cables and no dice. 
The log.txt (from config folder of sys-con) says that the controller was recognized (as Xbox One controller), so I'm attaching this file too. 

![Picture 1](https://user-images.githubusercontent.com/68853515/88539171-0a0f0780-d011-11ea-9901-469becf9e00d.jpg)
[log.txt](https://github.com/cathery/sys-con/files/4981847/log.txt)

**Comment by cathery** [comment]
There's currently an unknown problem with latest xbox controller firmware causing issues. 
Try these things:
- Press the xbox button so it starts blinking, then plug the controller into the switch
- Connect your controller through USB to your PC, then to your switch
- Use the Xbox Accessories app for Windows to reinstall controller firmware, then connect the controller to the switch

**Comment by SteinsM4te** [comment]
Plugging the controller to PC and then to Switch fixed the issue. Thank You.
