### ISSUE TITLE
SX OS Support?

### ISSUE THREAD

**Issue by magumboi** [cathery/sys-con#208]
Maybe? Someday? or is it impossible?

**Comment by cathery** [comment]
Not impossible, just a pain in the ass to maintain. This goes for other CFWs as well. I'm not willing to support it.

**Comment by AzukaChan** [comment]
@magumboi https://github.com/AzukaChan/sys-con-SXOS - Check the release section, fully SXOS compatible.
@cathery appreciate your work, but saying its "a pain in the ass to maintain" is a bit of a stretch.
