### ISSUE TITLE
Add support for Xbox One S Controller with firmware 4.8.1923.0

### ISSUE THREAD

**Issue by renA21** [cathery/sys-con#209]
**Description**
sys-con doesn't seem to work on an Xbox One S Controller with the latest firmware (version 4.8.1923.0). The controller is able to be recognized in HOS but can't receive any input at all.

**Environment**
- HOS 10.1.0
- Atmosphere 0.14.1
- sys-con 0.6.2

**Comment by cathery** [comment]
#100 
known issue
