### ISSUE TITLE
Sys-con on Sx-Os ?

### ISSUE THREAD

**Issue by Sanjaro-42** [cathery/sys-con#21]
I saw on the last update of the SX that they added the flags modules, I wonder if we can use Sys-Con with the SX-OS ?

PS: @cathery you are too strong.

**Comment by Sanjaro-42** [comment]
EDIT : You just have to change the name of the NSP to exefs.nsp.

**Comment by JonJaded** [comment]
Yeah, people mentioned it working fine on the reddit. Remember to close if no other questions :)

**Comment by cathery** [comment]
Released [0.2.3.1](https://github.com/cathery/sys-con/releases/tag/v0.2.3.1) in attempt to fix the issue
