### ISSUE TITLE
Support for AM 0.14 in 10.1.0?

### ISSUE THREAD

**Issue by zorropopo** [cathery/sys-con#211]
Is there a way to get syscon to work with ams 0.14 fw 10.0.1?

**Comment by amit27592** [comment]
I'm on v10 and it's working for me.

**Comment by FaserF** [comment]
It's working on AM0.14 and 10.1.0

But it needs to be rebuild for AM 0.16 and 11.0.0

Are there any plans on that?

**Comment by cathery** [comment]
The latest release seems to work both on 10.x.x and 11.x.x for me. Using the AMS 0.16.0 pre-release (7336dc2b)

**Comment by FaserF** [comment]
Thanks for testing it. This homebrew was the only one that was holding me back to upgrade to 0.16.0
I will give it a try
