### ISSUE TITLE
Xbox controller not working

### ISSUE THREAD

**Issue by mendav79** [cathery/sys-con#212]
**Description**
My Xbox one X controller (the third version with BT and Sync Button) don't work( neither dock or hanheld with otg) wired it gets recogniced in the switch like USB and a controller icon but any buttons work.
The Xbox controller is updated to Latest firmware with Xbox accesories app on windows

**Environment**
- Latest
- Latest
- Latest
- I have missioncontrol and It works perfect BT docked and hanheld

**Comment by cathery** [comment]
There's currently an unknown problem with latest xbox controller firmware causing issues. 
Try these things:
- Press the xbox button so it starts blinking, then plug the controller into the switch
- Connect your controller through USB to your PC, then to your switch
- Use the Xbox Accessories app for Windows to reinstall controller firmware, then connect the controller to the switch

**Comment by mendav79** [comment]
The method of connecting from pc and later from switch fixed both docked and hanheld Mode thanks a lot
