### ISSUE TITLE
HORI Wireless Horipad right stick randomly drifts 

### ISSUE THREAD

**Issue by MarkoVu12** [cathery/sys-con#213]
Hello!
I'm having this annoying problem since last year or so, only with a right stick randomly drifting up or down without any button being pressed. Other controllers works perfectly when this one is connected.
Any help? Thanks.
![aee04f4a-e89b-577d-b7ec-2cacb7ce2b5d](https://user-images.githubusercontent.com/34967638/93022392-7bb70b00-f5e9-11ea-9472-b1159edc9d16.jpg)

**Environment**
-  Firmware version 10.1.0
- Your version of Atmosphere 0.14.2
- Version of sys-con 0.6.2
- If you have any other sysmodules enabled, list them here. None

**Comment by cathery** [comment]
Doesn't this controller run natively on the switch? Does it occur without sys-con enabled?

**Comment by MarkoVu12** [comment]
Thanks for the reply! Yes it does run natively.  Yes, it only happens when sys-con is enabled :/

**Comment by cathery** [comment]
Are you sure your right stick isn't just drifting by itself? If it's wireless, sys-con cannot do anything to affect that

**Comment by MarkoVu12** [comment]
Yep. And this is the only one sys that i have enabled. I also tried with fresh sd card and only adding sys-con but this bug keeps coming. Also so drifting on OFW. Thanks ❤

**Comment by cathery** [comment]
Just to be clear, are you using this controller in wireless mode?

**Comment by MarkoVu12** [comment]
Yes

**Comment by cathery** [comment]
Then this can't be a sys-con issue, because sys-con doesn't support bluetooth right now. You could try to go to Settings -> Controllers and Sensors -> Calibrate Control Sticks and see if that helps
