### ISSUE TITLE
Error creating interface for product 654 with error 369

### ISSUE THREAD

**Issue by miltoncandelero** [cathery/sys-con#22]
+ Switch: 8.1.0
+ Atmosphere: 0.9.4
+ sys-con: 0.2.3

One of my xbox 360 controllers gives off this error.
The gamepad in question was always recognised as a original 360 controller by both xbox consoles and pcs but I always tought it was an really good clone.

Anyway I checked the logs and the error is:
`Error creating interface for product 654 with error 369`
A bit criptic to me but maybe it can help. Also, it seems that after the error retries and fails again.
Here it is the full log:
Steps for this log:
1. Delete previous log.
2. Unplug working 360 controller
3. Plug working 360 controller
4. Plug non working 360 controller
5. Wait a while
6. Unplug non working 360 controller

Anything I can do to help let me know.

[log.txt](https://github.com/cathery/sys-con/files/3817734/log.txt)

**Comment by miltoncandelero** [comment]
extra information: The error persists if the only controller connected is the non working one

**Comment by Gullib** [comment]
i get this same error but with a different product. ( Guess it can be because I have an xbox one controller)

**Comment by ouruoliang** [comment]
I also get the exact same error with a wired Xbox 360 controller. Always been recognized as genuine but I bought it here online in China so might be a good quality fake?

I'm on the latest Kosmos 14.2 and the switch is on 9.0.1.
Anyway, this is the error that keeps going on infinitely:

`2019-10-07 00:00:00: Succeeded event 1118
2019-10-07 00:00:00: Interfaces size: 0; capacity: 8
2019-10-07 00:00:00: Error creating interface for product 654 with error 369
2019-10-07 00:00:00: Interface state was changed
`

I've tried reinstalling Kosmos, setting my date/time to the correct time (who knows.) and renaming sys-con.nsp to exefs.nsp but nothing works, the same error keeps appearing in the log while the controller is never recognized. The xbox button lights up though, it sometimes stays on, or it goes on that forever on/off blinking.

**Comment by cathery** [comment]
This is not your fault. Try this version and tell me if it works https://files.catbox.moe/zfodfx.rar

**Comment by ouruoliang** [comment]
Hey, It instantly worked! You're a god!

Should I only use this version or will the future updates include the "fix" you just gave us? The xbox button acts as the switch "home" button that takes you back to the main switch menu. Also the xbox button does keep blinking so not sure what to do about this but I thought you'd like to have a bit of feedback!

Thank you so much again for everything!

**Comment by cathery** [comment]
You'll have stick drifting as you don't have the necessary config files. The blinking is taken care of. Expect a release soon.

**Comment by ouruoliang** [comment]
Hey hi again! Yeah sorry for the spam but I just checked it out and the left stick drifts towards the bottom-left direction. It does on Luigi but does not on Zelda's Link Awakening nor Untitled goose game. No rush and thanks for everything!

**Comment by cathery** [comment]
@miltoncandelero Have you checked if it works properly on release [3.0.0](https://github.com/cathery/sys-con/releases/tag/v0.3.0)?
