### ISSUE TITLE
Xbox one controller not working

### ISSUE THREAD

**Issue by Gullib** [cathery/sys-con#23]
I tried the sys module and reeboted the console. It didnt work. I have a regular xbox one controller and i pluged it to my switch in handheld mode. Im on ams 9.0.1

**Comment by tiliarou** [comment]
What is your HOS version ?

**Comment by cathery** [comment]
Try [0.2.3.1](https://github.com/cathery/sys-con/releases/tag/v0.2.3.1)

**Comment by uptownboy** [comment]
same happen to me. Xbox one controller not working, ver.0.2.3.1

**Comment by cathery** [comment]
Do you have Atmosphere CFW installed?

**Comment by DrHacknik** [comment]
This does not also work with the Power-A Xbox One controller. It should yet it isn't. 
Running the latest Atmosphere and Firmware 9.0.1

**Comment by vassall89** [comment]
I had the same problem but with version 3.0 it work make sure to press the xbox button to turn on the controller when it starts flashing plug the cable that worked for me

**Comment by Slluxx** [comment]
xbox one s, 8.1 and newest release doesnt seem to work for me

**Comment by coggy9** [comment]
I also have this issue, with 0.3.0, latest Atmosphere and firmware 8.1. Using a 2nd gen/Bluetooth capable Xbox One controller that came with my One X.
