### ISSUE TITLE
Will there be any news on xbone wireless dongles?

### ISSUE THREAD

**Issue by Sumpftier** [cathery/sys-con#230]
(Sry for wrong format usage I couldn't do it any other way)

**Comment by cathery** [comment]
Use Discussions next time. Wireless dongles proved to be a pain/impossible to add so I gave up on them. Maybe someone else can implement them and create a PR. If you have a compatible Xbox One Controller you can use [MissionControl](https://github.com/ndeadly/MissionControl) for now.
