### ISSUE TITLE
Build is a mess

### ISSUE THREAD

**Issue by Wat6656** [cathery/sys-con#244]
**Description**
building this app is a mess. getting not defined errors for the battery and joysticks.  i would assume those are in the switch.h file, which i cant find anywhere.

**Comment by doctor-amaton** [comment]
You're probably using incompatible versions of libnx/stratosphere. You have to switch to the branch new_dev, which uses the most recent one (there are some breaking changes). At least, that's how I managed to get my builds working

**Comment by Wat6656** [comment]
Thanks! will give it a shot.

**Comment by Wat6656** [comment]
thank you doctor-amaton, worked!!!

**Comment by miguel-amaton-sp** [comment]
Glad to know! looking forward for your PRs in the future 👀
