### ISSUE TITLE
To add a USB Racing Wheel e.g. Thrustmaster T150 PRO

### ISSUE THREAD

**Issue by tabnk** [cathery/sys-con#260]
**Description**

I'm planning to add Thrustmaster T150 PRO (Racing Wheel) to sys-con so that I don't need to use Brook Ras1ution Converter. Are these all source files that need to be modified? 

![image](https://user-images.githubusercontent.com/10874582/126884293-b1ff65d8-fa0d-4dd8-9d28-f705acbfdaaa.png)

**Comment by PieroBarcellos** [comment]
Did you have success with this?

**Comment by JQOz** [comment]
Any success?

**Comment by o0Zz** [comment]
@tabnk  I actively maintain a fork of this project, I built a new version that support all controllers which are compatible natively with a PC (With HID Profile) -> https://github.com/o0Zz/sys-con/releases.
I successfully tested my driver with a wheel (Logitech Driving Force GT), thus if your controller is also an USB controller with an HID profile it should works. Let me know

**Comment by tabnk** [comment]
> @tabnk I actively maintain a fork of this project, I built a new version that support all controllers which are compatible natively with a PC (With HID Profile) -> https://github.com/o0Zz/sys-con/releases. I successfully tested my driver with a wheel (Logitech Driving Force GT), thus if your controller is also an USB controller with an HID profile it should works. Let me know

Just tested your new sys-con. It only work partially. I added the following  setting just below [046d-c294]; Logitech Driving Force GT (Wheel). However only D-Pad work. So i tried another way by replacing your [default] with the below button ID, now the button work but doesn't match the T150 Pro PC mapping. Basically A button became L button. 



So there were two problems. Namely unable to find my [044f-b677] and button mapping is wrong.


BTW, log_level=0 or log_level=1 didn't generate any log.txt file.

[044f-b677]; Thrustmaster T150 PRO (Wheel)
B=6
A=5
Y=4
X=3
L=1
R=2
ZL=10
ZR=9
minus=7
plus=8

**T150 Pro Mapping:**
<img width="864" alt="image" src="https://github.com/cathery/sys-con/assets/10874582/8b6d02fc-d739-4214-8698-bd1d0d89190e"

[config2.txt](https://github.com/user-attachments/files/15544991/config2.txt)
>
[config1.txt](https://github.com/user-attachments/files/15544983/config1.txt)

**Comment by o0Zz** [comment]
Hi, 

I'm not sure where you get this picture with PC key binding, but I think it's incorrect. try this method: 
https://github.com/o0Zz/sys-con?tab=readme-ov-file#method-1-from-a-windows-pc.

Regarding the logs, you're right I just found an issue where log file is not properly created. what you can do is create an empty file manually in "/config/sys-con/log.log" and it will be filled properly (I will fix it in next version)

Thanks

**Comment by tabnk** [comment]
I did use the Method 1. Later I found the PC mapping image from website and there matched too. 

And about the Hardware IDs. Switch detected a different ID as compared to the PC so that explain why unable get T150 Pro key setting.

Since Hardware IDs is different from PC side perhaps key mapping could be different. As for now, I trying to figure out button code and fix the setting.


[log.log](https://github.com/user-attachments/files/15571627/log.log)

Your log.log file .... Trying to find configuration for USB device: [044f-b65d] ...
<img width="1072" alt="image" src="https://github.com/cathery/sys-con/assets/10874582/c12bda9d-a834-44e0-837f-97ef25bf3dc0">

**Comment by tabnk** [comment]
Got it working now. As expected both [044f-b677] and [044f-b65d] actually got different button ID. Anyway New Button ID Below.

Tested on Mario Kart 8. It work very well except **HOME button** not responding to my wheel controller. And also little difficult to adjust the wheel to align it center because a bit of turning, it will turn in game wheel. So should I change stick_deadzone or trigger_deadzone for this or something else?

[044f-b65d]; Thrustmaster T150 PRO (Wheel)
B=2
A=3
Y=1
X=4
L=5
R=6
ZL=7
ZR=8
minus=9
plus=10
home=13

**Comment by o0Zz** [comment]
Perfect thank you for the key mapping I will add it to next release.

Yes you can play with stick_deadzone to deal with the turning issue but a side effect might be to have to turn more the wheel to take the input into consideration.  Try to play with it and let me know. 

Regarding different vendor_id/product_id its curious. Do you have a driver installed on your PC for this Thrustmater ? Actually the VID/PID you got on the switch seems to be a generic "Thrustmaster FFB Wheel" - While on your PC it seems to be a VID/PID for your model specifically. That probably why you got a different binding.

**Comment by tabnk** [comment]
Yes, I need to uninstall the T150 Pro driver to get generic key mapping button id. I will try change stick_deadzone to get suitable turning for me. 

About HOME button I try to map it to button 13 (PS button on T150 Pro) but it doesn't work. Is HOME button implemented?

**Comment by tabnk** [comment]
Fyi, the **BSP-D9 Mobile Phone Stretch Game Controller** work out of the box too. Detected as [045e-028e] a Xbox 360 Controller.

Actually the log.log file detected as a [054c-05c4]; DS4 v1 first and than it auto unplug and redetected as a [045e-028e] a Xbox 360 Pad.
<img width="652" alt="image" src="https://github.com/cathery/sys-con/assets/10874582/7e568021-4065-4942-9c7b-086efaf5dbd2">

**Comment by tabnk** [comment]
Regarding stick_deadzone for Mario Kart 8 only. 

Value 21-30 very little different from 20 or perhaps no at all.

**Value 32-35 it is what I want.** 

Value 40-50 way to high.

**Comment by o0Zz** [comment]
Thank you for the update ;)
Regarding HOME button, you're right I missed this one, it will be possible to map it in the next release.

**Comment by o0Zz** [comment]
Hi tabnk, 

A new release is available -> https://github.com/o0Zz/sys-con/releases/tag/1.1.0
This release should fix your home button issue.
I also natively integrated your controller.

Thus the assumption is, this controller should natively work on the latest release ;)
I will not communicate anymore on this thread, if you meet new issues, please open a ticket on my github, it will be easier for me to follow it ;) https://github.com/o0Zz/sys-con/issues

Thanks
