### ISSUE TITLE
Xbox One Wireless Adapter Compatibility

### ISSUE THREAD

**Issue by phobos85br** [cathery/sys-con#277]
Hi, I would ask if is it possible to make Sys-Con compatible with older Xbox One Controllers.

Those older models don't have the Bluetooth feature (Mission Control) but it uses a Wireless Dongle to connect to PC, like the Xbox 360 Dongle (wich Sys-Con alrteady supports).

Thank you in advance and make myself available to help with whatever is needed!

**Comment by JeBronLvmes** [comment]
@phobos85br  Were you able to resolve the issue? My xbox one adapter doesn't even light up when I plug it in but plugging in the controller directly works fine.

**Comment by eaglezoli** [comment]
> [@phobos85br](https://github.com/phobos85br) Were you able to resolve the issue? My xbox one adapter doesn't even light up when I plug it in but plugging in the controller directly works fine.

Same no light, did you ever find a fix? @JeBronLvmes @phobos85br
