### ISSUE TITLE
use Flash Disk instead of sdcard ?

### ISSUE THREAD

**Issue by sulthonuladib** [cathery/sys-con#286]
**Description**
Can i use flash disk instead of sdcard ?

**How to reproduce**

**Environment**
- Your Switch Firmware version
- Your version of Atmosphere
- Your version of sys-con
- If you have any other sysmodules enabled, list them here.

**Comment by SpaimaFemeilor** [comment]
Why tho? 
And no, you cant. atmosphere can only boot from sd card from hekate
