### ISSUE TITLE
My two Xbox one PDP controllers doesn't work 

### ISSUE THREAD

**Issue by BigBoss320** [cathery/sys-con#296]
**Description**
My two controllers are recognized as wired controllers but none of the button works. I think it's due to the non-official controllers. The two are PDP Xbox one controllers. 

**How to reproduce**
Connect the wired controller to the switch (docked or not) 

**Environment**
- Firmware 14.1.1
- Atmosphere 1.3.2
- Sys-con 0.6.4
- Other sysmodules enabled : SysDVR, Emuiibo, MissionControl. (and sysclk but was installed after the bug)

**Comment by ImagineA1m** [comment]
Same bro its xbox

**Comment by BigBoss320** [comment]
It seems that PDP have a big problem with that Module. Is is still in development ? Will you work on this issue ? Here are the models i have : 

PDP Afterglow Wave
![image](https://user-images.githubusercontent.com/44122706/224819309-22500c9a-8a46-47f3-a0ac-7118f9f996f6.png)

PDP Ghost White :
![image](https://user-images.githubusercontent.com/44122706/224819493-018f8199-723b-45ff-9b42-caaf46d60f26.png)

**Comment by o0Zz** [comment]
Update for others players, BigBoss320 di an awesome debug work and now this controller works on this fork -> https://github.com/o0Zz/sys-con/releases

**Comment by BigBoss320** [comment]
Yes, problem fixed on the newest update on the project continued by oOZz. Here is the issue : https://github.com/o0Zz/sys-con/issues/9
