### ISSUE TITLE
Xbox One Titanfall 2/PDP/PowerA controllers support

### ISSUE THREAD

**Issue by EzioisAwesome56** [cathery/sys-con#30]
i assume wired xbox one controllers are different from wireless ones that you use with a micro usb cable, as when i go to plug in my controller, its little light never lights up and its buttons do nothing.

I know the sys-module itself is functional, as using a dualshock 3 over usb works as intended.

if it helps any, i _think_ the ids for my controller are VID_24C6 and PID_543A

**Comment by cathery** [comment]
It seems you have a PowerA controller. It's not yet recognized, but I'm planning to add this soon. Can you launch this applet and send me a screenshot of your scan? Make sure only the PowerA controller is connected. 
https://files.catbox.moe/re60qo.rar

**Comment by EzioisAwesome56** [comment]
heres the ouput of that homebrew, dunno why theres 3 things when only the xbox controller is plugged in but
![2037080908400600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/21185626/68434710-a2194800-0187-11ea-853f-1c80dd20c2ac.jpg)

**Comment by cathery** [comment]
Each device can have multiple interfaces, this is normal. Give me a moment

**Comment by cathery** [comment]
Can you try this version of the sysmodule? https://files.catbox.moe/p7mpg3.rar

**Comment by EzioisAwesome56** [comment]
unfortuantly, that did not seem to work. the light still does not activate, nor do the buttons register anything.

(the rest of the module is working, so its installed right)

**Comment by cathery** [comment]
Can you send me the log? It's located at `sdmc:/config/sys-con/log.txt`

**Comment by EzioisAwesome56** [comment]
ignore the fact the date is in 2037; side effect of running linux on switch i never bothered to correct.
[log.txt](https://github.com/cathery/sys-con/files/3822319/log.txt)

**Comment by cathery** [comment]
Can you try this version? https://files.catbox.moe/5zbqou.rar

**Comment by EzioisAwesome56** [comment]
still doesnt work. However, plugging in the controller makes the little controller icon appear in the bottom left, and unplugging it makes it go away. Light on controller still doesnt come on and buttons still do nothing, however.

heres the log file for that run also, i unplugged it and plugged it back in a few times also.
[log.txt](https://github.com/cathery/sys-con/files/3822560/log.txt)

**Comment by cathery** [comment]
It seems like it has a different implementation from the official Xbox One controller. It's a shame, but maybe i'll see if i can adjust to it

**Comment by cathery** [comment]
Tell me if this build works https://files.catbox.moe/nefssl.rar

**Comment by EzioisAwesome56** [comment]
unfortunately this appears to have the same result as last time, little controller icon on bottom left, but no light and buttons don't work.

newest log file:
[log.txt](https://github.com/cathery/sys-con/files/3822901/log.txt)

**Comment by cathery** [comment]
Small revision https://files.catbox.moe/fx4gyr.rar

**Comment by Milenko7** [comment]
I bought one of these today and that last revision also gives me the icon at botom left but no response
https://www.ebgames.com.au/product/xbox-one/234754-xbox-one-wired-controller-white

**Comment by Milenko7** [comment]
[log.txt](https://github.com/cathery/sys-con/files/3823319/log.txt)
![2019110818053200-DA63280140B1530CD17755515D814CFE](https://user-images.githubusercontent.com/37691209/68456880-10770c80-0253-11ea-88a2-e8d44fe2fcfd.jpg)

**Comment by EzioisAwesome56** [comment]
> I bought one of these today and that last revision also gives me the icon at bottom left but no response

same deal here, icon in left, no light or button responses on newest build
[log.txt](https://github.com/cathery/sys-con/files/3823473/log.txt)

**Comment by cathery** [comment]
Can you tell me if this build works? https://files.catbox.moe/ksumxe.rar

**Comment by Milenko7** [comment]
Works amazing!
Everything I tried works except for Binding of isaac doesn't register inputs

**Comment by cathery** [comment]
yooo

**Comment by Milenko7** [comment]
Tried Goose game, DKC tropical, saint's row, diablo 3, monkey ball, link's awakening, retroarch, gzdoom, & quake and all worked perfect, but yeah binding of isaac wouldn't respond to anything

Amazing work cathery :):)

**Comment by Milenko7** [comment]
Ah looks like it had a day 1 update to add support!

**Comment by cathery** [comment]
@Milenko7 can you try this version to make sure it still works? https://files.catbox.moe/30byxg.rar

**Comment by Milenko7** [comment]
Yep works fine!

**Comment by cathery** [comment]
Great! @EzioisAwesome56 Please let me know if your controller works with this version https://files.catbox.moe/30byxg.rar

**Comment by Txustra** [comment]
My PDP controller (same as @Milenko7 ) does not work. The Switch recognise it and shows it in the controller screen as USB, but inputs do not work.

**Comment by Milenko7** [comment]
@Txustra Are you using this one? https://files.catbox.moe/30byxg.rar
I have to unplug and plug it back in after it's on the homescreen then press the xbox button for it to start working

**Comment by cathery** [comment]
That should be fixed in release [0.4.0](https://github.com/cathery/sys-con/releases/tag/0.4.0), Does it not work still?

**Comment by Txustra** [comment]
Still not working for me with that revision nor 0.4.0 :<

**Comment by cathery** [comment]
@Txustra Does this version work? https://files.catbox.moe/tzw5v7.rar

**Comment by Txustra** [comment]
It does not work yet even Switch recognises it... dunno what's happening

**Comment by Txustra** [comment]
> @Txustra Does this version work? https://files.catbox.moe/tzw5v7.rar

It does not work yet even Switch recognises it... dunno what's happening

**Comment by cathery** [comment]
It seems your PDP controller needs to be sent a driver-specific packet before it starts working. Without knowing what it is, I can't support that controller. Can you download this diagnostics tool and tell me what your controller's VID and PID are? https://files.catbox.moe/re60qo.rar

**Comment by Txustra** [comment]
Sure:
![image](https://user-images.githubusercontent.com/21977887/68528296-17545c80-02f1-11ea-9511-e2f1c76b625d.png)

**Comment by cathery** [comment]
It looks like your controller has the same 2 interfaces as Milenko's controller, so it should work the same. This version tries to use the third one, but i doubt it will work https://files.catbox.moe/tzw5v7.rar

**Comment by Txustra** [comment]
You are right... I don't know what's the problem then...

**Comment by EzioisAwesome56** [comment]
Sorry for this late reply, life got in the way yesterday.

That build you linked when you pinged me unfortunately does not working with my controller. Little controller icon in the left but no light or buttons yet still.

Heres the newest log file: 
[log.txt](https://github.com/cathery/sys-con/files/3827759/log.txt)

**Comment by cathery** [comment]
Can you test this build? https://files.catbox.moe/3e0jbl.rar

**Comment by EzioisAwesome56** [comment]
still doesnt work, controller icon appears in the bottom but buttons do not register + led does not turn on. However, the xbox button appears to register being pressed, as it seems to make the controller icon disappear for a moment after being pressed, then pop back up after a while
[log.txt](https://github.com/cathery/sys-con/files/3827859/log.txt)

**Comment by cathery** [comment]
The Xbox button sends a verification request to the host and turns off if it doesn't respond. That just means there's no actual communication going on. Do you know if it disappeared on previous builds too?

**Comment by EzioisAwesome56** [comment]
> 
> 
> The Xbox button sends a verification request to the host and turns off if it doesn't respond. That just means there's no actual communication going on. Do you know if it disappeared on previous builds too?

im unsure, i can go grab an earlier build and test it real fast

**Comment by cathery** [comment]
Try this version: https://files.catbox.moe/sw1b9n.rar

**Comment by EzioisAwesome56** [comment]
same result as last time, no led, no button registers, controller icon and xbox button shows same behavior as last time
[log.txt](https://github.com/cathery/sys-con/files/3827912/log.txt)

**Comment by cathery** [comment]
Try this one: https://files.catbox.moe/ehjdrw.rar

**Comment by EzioisAwesome56** [comment]
This time the controller's little LED turned on, but none of the buttons work. The xbox button still makes the controller icon disappear and reappear also.
[log.txt](https://github.com/cathery/sys-con/files/3827929/log.txt)

**Comment by cathery** [comment]
Alright, we're getting somewhere! Try this build https://files.catbox.moe/wbf85d.rar

**Comment by EzioisAwesome56** [comment]
uh, now the LED doesnt turn on at all...weird

buttons still do nothing and xbox button has same behavior as before
[log.txt](https://github.com/cathery/sys-con/files/3827935/log.txt)

**Comment by cathery** [comment]
This one tries just about every init packet i can think of: https://files.catbox.moe/2to2tu.rar

**Comment by EzioisAwesome56** [comment]
alright, this time the led comes on, but no buttons do anything. HOWEVER, pressing the xbox button does NOT make the controller icon go away, instead remaining on the entire time.
[log.txt](https://github.com/cathery/sys-con/files/3827959/log.txt)

**Comment by cathery** [comment]
Alright, I've changed some packets around https://files.catbox.moe/mv9beh.rar

**Comment by EzioisAwesome56** [comment]
same result as the last build, i also tried both usb ports and it still does not register inputs.
[log.txt](https://github.com/cathery/sys-con/files/3827973/log.txt)

**Comment by cathery** [comment]
So the controller doesn't go away when you press the button? cool

**Comment by EzioisAwesome56** [comment]
> 
> 
> So the controller doesn't go away when you press the button? cool

nope, it stays now, it just doesnt send inputs for some reason

**Comment by cathery** [comment]
Trying to narrow down the packets that work, try this one https://files.catbox.moe/aq1z8x.rar

**Comment by EzioisAwesome56** [comment]
that build still has the led come on, and pressing xbox doesnt make the controller icon go away.
I doubt you need the log for this but here you go anyway
[log.txt](https://github.com/cathery/sys-con/files/3827982/log.txt)

**Comment by cathery** [comment]
Try this https://files.catbox.moe/zl0f14.rar

**Comment by EzioisAwesome56** [comment]
that build has the xbox button make the controller icon go away and then come back again. It also seems to do this after a little bit of waiting without pressing the button.
[log.txt](https://github.com/cathery/sys-con/files/3828005/log.txt)

**Comment by cathery** [comment]
Alright! Try this one then https://files.catbox.moe/ik2h0n.rar

**Comment by EzioisAwesome56** [comment]
it appears to be exhibiting the same behaviors as the last build, both the xbox button and waiting a bit makes the controller icon go away. The led also turns off when this happens
[log.txt](https://github.com/cathery/sys-con/files/3828011/log.txt)

**Comment by cathery** [comment]
Hmm alright, try this combination https://files.catbox.moe/50zhwp.rar

**Comment by EzioisAwesome56** [comment]
no, that still seems to suffer from both the xbox button and waiting make the controller icon disappear and reappear

it should also be noted that when the little light comes on, a tiny vibration can be felt, if that means anything
[log.txt](https://github.com/cathery/sys-con/files/3828015/log.txt)

**Comment by cathery** [comment]
The vibration can be felt regardless of the sysmodule. It's just how the switch dock works, even without the switch. Alright, I 100% expect this to leave the light on https://files.catbox.moe/7mckgf.rar

**Comment by EzioisAwesome56** [comment]
as far as i can tell, youd be correct. waiting or the xbox button keeps its light on.

heres the log also if you need it for anything at all
[log.txt](https://github.com/cathery/sys-con/files/3828022/log.txt)

**Comment by cathery** [comment]
Cool, so I've narrowed that down, let's see if this changes anything: https://files.catbox.moe/7lb5mc.rar

**Comment by EzioisAwesome56** [comment]
seems to make no different. LED stays on, controller icon doesnt disappear, but inputs do nothing.
[log.txt](https://github.com/cathery/sys-con/files/3828028/log.txt)

**Comment by cathery** [comment]
Cool! And if i do this? https://files.catbox.moe/7z21da.rar

**Comment by EzioisAwesome56** [comment]
same results as last build. just to be sure i unplugged it and plugged it back in, no change. light stays on, no inputs work, etc
[log.txt](https://github.com/cathery/sys-con/files/3828032/log.txt)

**Comment by cathery** [comment]
Does it work still? https://files.catbox.moe/wf78gk.rar

**Comment by EzioisAwesome56** [comment]
that still keeps the led on and stuff, but inputs are still non-functional.
[log.txt](https://github.com/cathery/sys-con/files/3828056/log.txt)

**Comment by cathery** [comment]
Check this one https://files.catbox.moe/ko13p8.rar

**Comment by EzioisAwesome56** [comment]
that one actually doesnt turn on the LED, but the controller icon never disappears oddly enough. inputs still do not function though
[log.txt](https://github.com/cathery/sys-con/files/3828065/log.txt)

**Comment by cathery** [comment]
Okay this may be a stretch, but do you know if you can install a firmware update to your controller?

**Comment by EzioisAwesome56** [comment]
uhh, i dunno if thats even possible, this is branded an an amazon controller and i doubt theres firmware updates for it anywhere

**Comment by cathery** [comment]
It says it's licensed by Xbox. If you're on Windows 10, there's an app on the Microsoft Store called Xbox Accessories that lets you update firmware. See if your controller gets recognized

**Comment by EzioisAwesome56** [comment]
it appears to recognize the controller, the button test works, but i cant seen to find a update option.
It does display the firmware version in this picture, though.
![2037080908400600-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/21185626/68539271-f02c7800-034e-11ea-9ca0-53b64c095277.jpg)

**Comment by cathery** [comment]
Seems like it doesn't let you update. It lets me press on the firmware version text

**Comment by EzioisAwesome56** [comment]
would updating the firmware have helped at all, or is this just part of troubleshooting?

**Comment by cathery** [comment]
Well I was wondering if the non-working controllers have had a lower firmware version, but you can't update your so it's still an issue

**Comment by cathery** [comment]
I don't remember if I tried this version, this one sends the same packets as the release with a slight modifier, let me know if it works https://files.catbox.moe/1usuab.rar

**Comment by EzioisAwesome56** [comment]
unfortunately that build does not work, and now the led doesnt come on, and the xbox button makes the controller icon disappear. no other inputs do anything either
[log.txt](https://github.com/cathery/sys-con/files/3828562/log.txt)

**Comment by cathery** [comment]
Does this one work? https://files.catbox.moe/3o3431.rar

**Comment by EzioisAwesome56** [comment]
no, that appears to exhibit the same behaviors as the previous build, no led, xbox disconnects it, no inputs
[log.txt](https://github.com/cathery/sys-con/files/3828587/log.txt)

**Comment by cathery** [comment]
Alright, I added a logger for all input packets sent from the controller, it's probably gonna bloat your log file but i need it to make sure: https://files.catbox.moe/vaclhw.rar

**Comment by EzioisAwesome56** [comment]
that build still didnt turn the led on, but pressing xbox didnt make the controller disconnect. oh, and the inputs still didnt respond
[log.txt](https://github.com/cathery/sys-con/files/3828629/log.txt)

**Comment by cathery** [comment]
Someone reported that this build is working, can you try it? https://files.catbox.moe/1wse26.rar

**Comment by EzioisAwesome56** [comment]
well, besides the LED not coming on, inputs do appear to be functional at last in the home menu, and also in games such as Mario Kart 8, Cave story plus and Luigi's mansion 3. At this point i suppose it doesnt matter if the led isnt on as the controller works.

heres the log if you need it for anything
[log.txt](https://github.com/cathery/sys-con/files/3828753/log.txt)

**Comment by cathery** [comment]
That's good. This build should enable LEDs https://files.catbox.moe/i3sbgz.rar

**Comment by EzioisAwesome56** [comment]
no, that one seems to have disabled inputs, as now its not working at all
[log.txt](https://github.com/cathery/sys-con/files/3828763/log.txt)

**Comment by cathery** [comment]
Alright if this one doesn't work, I'll compromise and settle on no LEDs https://files.catbox.moe/wjqqhh.rar

**Comment by EzioisAwesome56** [comment]
that one has no led and also no inputs, unfortunately
[log.txt](https://github.com/cathery/sys-con/files/3828772/log.txt)
.

**Comment by cathery** [comment]
Alright, I will include the working version in the release
