### ISSUE TITLE
Aftermarket DS3 Support

### ISSUE THREAD

**Issue by gilest** [cathery/sys-con#31]
This isn't a priority for me personally, but thought it might be useful to someone else. May as well be added eventually.

These are cheap DS3 controllers not manufactured by Sony.

![2019110814110500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/36919/68441034-b74ab100-0231-11ea-8f19-105b8d569f32.jpg)

**Comment by cathery** [comment]
I'm actually working on it!

**Comment by cathery** [comment]
By the way, the controller you have should technically get recognized as a Dualshock 3 controller. It has the same VID and PID. I have a similar controller that fakes itself and it's fully functioning

**Comment by gilest** [comment]
Ooops, yeah it works. I didn't actually test that 😅
