### ISSUE TITLE
Sys-con doesn't work on latest firmwares

### ISSUE THREAD

**Issue by chemaperez** [cathery/sys-con#320]
Sys-con 0.6.4 doesn't seem to work at all on latest firmwares. Tested on two different consoles (one in FW 16.0.2 with atmosphere 1.5.2 and the other in FW 16.0.3 with atmosphere 1.5.4).

Tested with controllers that worked ok on previous FW versions. Controllers are not recognized.

**Comment by CheezeDaCode** [comment]
Working for me in 16.0.2 AMS 1.5.5. Are you sure that it is installed correctly?

**Comment by chemaperez** [comment]
For me, Dualshock 3 works fine in 16.0.2 but not in 16.0.3.

**Comment by chemaperez** [comment]
I update my switch from 16.0.2 to 16.1.0  and AMS 1.5.5 and sys-con stopped recognizing the controller.

**Comment by chemaperez** [comment]
ok I found the problem, I will open another issue so it doesn't get lost.
