### ISSUE TITLE
3rd party Xbox 360 controller not working

### ISSUE THREAD

**Issue by CFHeadphase** [cathery/sys-con#34]
I've tried every USB port on the dock. No input is accepted, the LED in the middle just blinks.

It's an 'Afterglow for Xbox 360 PL-3702'.

I saw you had a diagnostic applet, so I ran that in case it helps:
![IMG_20191108_082139](https://user-images.githubusercontent.com/1280942/68461187-8eaac300-0201-11ea-8503-3f2636bf3704.jpg)

Thanks!

Edit: Logs attached:
[log.txt](https://github.com/cathery/sys-con/files/3823609/log.txt)

**Comment by cathery** [comment]
Can you tell me if this version works for you? https://files.catbox.moe/fx4gyr.rar

**Comment by CFHeadphase** [comment]
> 
> 
> Can you tell me if this version works for you? https://files.catbox.moe/fx4gyr.rar

Yeah, that works. Thanks!
