### ISSUE TITLE
Xbox one wireless adapter support

### ISSUE THREAD

**Issue by SWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI** [cathery/sys-con#36]
Would this work? In fact, could dedicated wireless adapters for other controllers work as well like the steam controller's adapter?

**Comment by cathery** [comment]
I don't know the specifics of the xbox one adapter, can you plug it into your switch and send me a screenshot of this applet after the scan? https://files.catbox.moe/re60qo.rar

**Comment by halop** [comment]
![switch_xboxone_dongle](https://user-images.githubusercontent.com/4215938/68494692-208ced00-024f-11ea-86af-ec4b9f7b7cc1.jpg)

(Original Xbox One Wireless Adapter)

**Comment by cathery** [comment]
I can't really say from here. Are you able to pair controllers when it's plugged in? If so, can you pair one of your controllers and send me another scan?

**Comment by halop** [comment]
Unfortunately it does not work.
Controller can't find the adapter when it is plugged into the switch.

**Comment by SWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI** [comment]
Ah, I was hoping this wasn't the case. I tried plugging mine into my switch
before and the light didn't come on. I thought it could be maybe fixed by
software but maybe not. Hopefully this isn't the case with the steam
controller but I haven't tested that yet but from what I remember, it
needed to install drivers on Windows to work.

**Comment by cathery** [comment]
This build should at least recognize the xbox one adapter, can you tell me if it recognizes the Xbox One controllers? If not, can you send me a scan of the connected devices? https://files.catbox.moe/enwhm8.rar

**Comment by SWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI** [comment]
Okay. I'm not home right now but I'll get back to you with results tonight.

**Comment by halop** [comment]
controller is not recognized with the new version,
output:
![switch_xboxone_dongle2](https://user-images.githubusercontent.com/4215938/68520983-bd29ac00-029c-11ea-93c4-6912eec961ec.jpg)

**Comment by SWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMI** [comment]
Oh, okay. It's not big deal. I also just tested the steam controller adapter and it didn't work.

**Comment by GeorgeCalderoESP** [comment]
I use a xbox 360 Wireless Receiver from Dealextream, bought about 10 years ago (or more). Do you need any log?

**Comment by Adubbz** [comment]
I believe the Xbox One wireless adapter is a bit more complicated than the 360 one. You might want to reference these:

https://github.com/360Controller/360Controller/pull/935
https://github.com/360Controller/360Controller/pull/950

**Comment by jhinl3m0n** [comment]
Some news for the xbox one adpter? Let us know if we can help you

**Comment by cathery** [comment]
It may take a while. See Adubbz's post, there's a lot to implement. I got myself a wireless adapter for testing (slim, looks like a usb stick) and I'm currently testing on it

**Comment by Exosq** [comment]
Hi, i have the first Xbox One wireless adapter and three different Xbox controller (Xbox One normal controller, Elite & Elite series 2) let me know if you need some testing as i would love to be able to play with them wirelessly on the switch :)

**Comment by cathery** [comment]
I can't seem to send more than 2048 bytes total to any output endpoint... The firmware needs 70k

**Comment by jhinl3m0n** [comment]
so its not possible ?

**Comment by jhinl3m0n** [comment]
any news with atmosphere 10.0?

**Comment by cathery** [comment]
Work on Xbox One Adapter will be suspended in favor of native Bluetooth support.

**Comment by Adubbz** [comment]
It’s worth noting that only new Xbox One controllers (after the Xbox One S was released) support Bluetooth. The original ones, and the revision after that, do not.

**Comment by halop** [comment]
unfortunately my xbox one controller does not work with bluetooth

**Comment by SmartBoy84** [comment]
So, does this work yet?

**Comment by Seelector0** [comment]
Hey! Thanks for your work, will work on this continue?
