### ISSUE TITLE
Xbox 360 (Gamestop) Controller flashing xbox logo and does not respond to any input

### ISSUE THREAD

**Issue by FoxPlayer1889** [cathery/sys-con#38]
i have a xbox 360 controller (gamestop) and tried connecting on the dock with the modules you released, but it doesn't work, tried rebooting and make sure that files are in the right place, nothing, also tried nacoon controller, doesn't work too

**Comment by cathery** [comment]
Does this build work? https://files.catbox.moe/qszbd6.rar

**Comment by FoxPlayer1889** [comment]
> Does this build work? https://files.catbox.moe/qszbd6.rar

Nope

**Comment by cathery** [comment]
Can you do a device scan with this applet and send me a screenshot? https://files.catbox.moe/re60qo.rar

**Comment by cathery** [comment]
Sorry, i forgot to rename the file in the last zip, can you try this one? https://files.catbox.moe/l5v1mf.rar

**Comment by FoxPlayer1889** [comment]
> Sorry, i forgot to rename the file in the last zip, can you try this one? https://files.catbox.moe/l5v1mf.rar

thanks, this version works love you! great work man!

**Comment by cathery** [comment]
Alright! This is the version used in 0.4.0. Closing now

**Comment by FoxPlayer1889** [comment]
-

> Alright! This is the version used in 0.4.0. Closing now

one last thing, is it possible to swap buttons? because the nintendo ones and xbox one are different.. you understand?

**Comment by cathery** [comment]
Yes, check the config files located at `sdmc:/config/sys-con/`
