### ISSUE TITLE
Dualshock 4 Implementation

### ISSUE THREAD

**Issue by cathery** [cathery/sys-con#4]
i don't have a dualshock 4

**Comment by GarnetSunset** [comment]
start a ko-fi and ill drop a fiver to making that happen

**Comment by cathery** [comment]
[![ko-fi](https://www.ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/H2H316ZQV)

**Comment by GarnetSunset** [comment]
ah i see my brain is tiny

ill drop a fiver :)

**Comment by cathery** [comment]
Thank you!

**Comment by GarnetSunset** [comment]
No problem! Have a great one!

**Comment by Neriek** [comment]
I'd loan you one of mine, but I get the feeling it'd be a pain to ship. But I can donate $5 when I get paid Friday if that helps.

**Comment by tiliarou** [comment]
Gonna donate as well, this module is amazing and deserves more support.

**Comment by xerpi** [comment]
https://github.com/xerpi/ds4vita/blob/master/main.c
and 
https://github.com/torvalds/linux/blob/master/drivers/hid/hid-sony.c
Might be useful

**Comment by cathery** [comment]
I just wanna let everyone know that dualshock 4 implementation is pretty much ready to publish, but due to firmware limitations i can't support both versions of the controller (CUH-ZCT1E and CUH-ZCT2E i think), so until I can figure it out, the release will be delayed.

**Comment by jsyreviews** [comment]
Thanks for all of your hard work Cathery, I always hoped that there will be a HID2VPAD equivalent for the Switch some day and you finally did it, Cheers!

**Comment by cathery** [comment]
Just making sure, does this work on anyone's 1st generation dualshock 4? https://files.catbox.moe/2yiw3y.rar

**Comment by david4444** [comment]
> Just making sure, does this work on anyone's 1st generation dualshock 4? https://files.catbox.moe/2yiw3y.rar

Mine is 1st generation I believe by the message you left before this one, And it works with this build. Buttons and the sticks. I don't have 2, So I can't test that.

**Comment by cathery** [comment]
Alright, thank you
