### ISSUE TITLE
Mayflash SEGA Megadrive Adapter! Works! (but requires analog keymap!)

### ISSUE THREAD

**Issue by Sonic2Retro** [cathery/sys-con#44]
Thanks to your awesome work, I connected SEGA Fighter Stick through Xinput Mayflash adapter and is now detected!
https://img.milanuncios.com/fg/2408/47/240847578_1.jpg?VersionId=uUIVO5R2DiZ1s0jc1F8Dy3RWGyR9Qtio

The only issue preventing it from working correctly is the joystick directions that need to be mapped as analog directions instead of DPAD:
; DPAD_UP	D-pad UP
; DPAD_RIGHT	D-pad RIGHT
; DPAD_DOWN   D-pad DOWN
; DPAD_LEFT	D-pad LEFT

For example they could be mapped like:
; AN_UP	Analog up UP
; AN_RIGHT	Analog RIGHT
; AN_DOWN	Analog DOWN
; AN_LEFT	    Analog LEFT

Or a setting that switches DPAD buttons with analog stick ones!

**Comment by cathery** [comment]
Thanks for your feedback. I'll try adding a config setting that makes dpad use the left stick instead.
