### ISSUE TITLE
 issue with new xbox one adapter (the slim one)

### ISSUE THREAD

**Issue by jhinl3m0n** [cathery/sys-con#45]
the new receiver (the slim one) isn't recognized at all, how i can help you to resolve the issue?

**Comment by cathery** [comment]
It's not implemented yet. It's being resolved in #36

**Comment by jhinl3m0n** [comment]
so i have to wait until u resolve it in the next post? how can i help you? if i can

**Comment by cathery** [comment]
I already have the adapter, so it's just a matter of time. I'll send a build in the other thread for testing to make sure it works.

**Comment by jhinl3m0n** [comment]
ty ur doing amazing work and ur so fast in a few days u make something that works rock solid and when not u are there all day to fix everything so ty from the community.
