### ISSUE TITLE
Xbox 360 Play and Charge Kit Support

### ISSUE THREAD

**Issue by noreason4** [cathery/sys-con#47]
I am specifically talking about this adapter: https://rukminim1.flixcart.com/image/416/416/gaming-adapter/charging-kit/e/b/v/b-v-g-xbox-360-play-charge-kit-original-imaehayfxr6ggr9w.jpeg?q=70

Its plugged into the top of the Xbox 360 wireless controller.

I just tested it and it does not work yet. LEDs just keep blinking.

Thank you!

**Comment by cathery** [comment]
According to #16, xbox 360 charge and play cable doesn't send any data, and it shouldn't work on PC either. You need a wireless adapter.

**Comment by noreason4** [comment]
Ah ok sorry I didn't know that. I only knew that I was able to play with this kit attached when no battery was installed in the controller. Guess it still used the wireless connection then and the cable only supported power. Thanks!
