### ISSUE TITLE
Not working with Thrustmaster GPX 360 joystick

### ISSUE THREAD

**Issue by Menaci** [cathery/sys-con#48]
1) HUGE thanks for your effort with this project.

2) My console is at ver 8.0.1. I'm trying to lend another joystick for testing.

**Comment by cathery** [comment]
Can you send me the log? It's located at `sdmc:/config/sys-con/log.txt`

**Comment by Menaci** [comment]
Tried the v0.2.3.1. It's sorted out now.

Anyway iI'll send you the 0.3 log as soon I get home.

**Comment by Menaci** [comment]
Haha! Just found out it was a file patch mistake.

The deal was: I've extracted different releases through my smartphone, and while trying to use the tinfoil for moving the file amid tests,  tinfoil happens to copy folders into subfolders with the same name.

Thanks for the attention.
