### ISSUE TITLE
Xbox One Elite controller not working

### ISSUE THREAD

**Issue by Lockheed-Martini** [cathery/sys-con#50]
Gets noticed (with the little controller plugged in icon) but no inputs work 
![2019110911230000-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/57572931/68534090-52e92980-02e5-11ea-808f-e4e5e47e2602.jpg)

**Comment by cathery** [comment]
Are you using 0.4.0? Can you send me the log located at `sdmc:/config/sys-con/log.txt`?

**Comment by Lockheed-Martini** [comment]
yes 4.0. 
[log.txt](https://github.com/cathery/sys-con/files/3827657/log.txt)

**Comment by cathery** [comment]
I see you've used it in previous versions, did it work then?

**Comment by Lockheed-Martini** [comment]
No has always just shown the icon for controller but no inputs work. Normal xbone controller works. Also I have 3 elite ones so it should not be a specific controller issue.

**Comment by cathery** [comment]
Can you try this build? https://files.catbox.moe/3e0jbl.rar

**Comment by Lockheed-Martini** [comment]
Still no inputs working. let me know if there anything I can do to further help.

**Comment by cathery** [comment]
I've got lots of builds to try if this doesn't work, try this one https://files.catbox.moe/sw1b9n.rar

**Comment by Lockheed-Martini** [comment]
That build actually neither elite nor regular worked. both just got noticed with controller icon

**Comment by cathery** [comment]
I have high hopes for this one: https://files.catbox.moe/ehjdrw.rar

**Comment by Lockheed-Martini** [comment]
sorry, again neither normal xbone controller or elite are working. just the controller icon shows up.

**Comment by Lockheed-Martini** [comment]
I switched back to your latest release 0.4.1 and normal xbone controller is working again however let me know if there is other builds to try for elite controller though!

**Comment by cathery** [comment]
Can you tell me if this does anything? https://files.catbox.moe/7z21da.rar

**Comment by Lockheed-Martini** [comment]
This seems like same result. Neither normal xbone or xbone elite controller have any inputs working.

**Comment by cathery** [comment]
What about this one? https://files.catbox.moe/wf78gk.rar

**Comment by Lockheed-Martini** [comment]
no sorry just gets noticed again for both

**Comment by cathery** [comment]
How about now? https://files.catbox.moe/ko13p8.rar

**Comment by Lockheed-Martini** [comment]
No, same result. Any other config or something i can send to help?

**Comment by cathery** [comment]
It's just baffling to me that the elite controller doesn't work. The regular one especially. Every single build I've sent works with my Xbox One S controller. Try this https://files.catbox.moe/qlyaeo.rar

**Comment by Lockheed-Martini** [comment]
im using really old first edition xbone controller if that makes a difference. ill try that build in a second, The actual release 0.4.1 works on it.

**Comment by Lockheed-Martini** [comment]
No sorry still just controller plugged in icon. I tried 2 different regular controllers (non S version) and 3 elite controllers and restarted the switched 2 times and had same result each time.

**Comment by Lockheed-Martini** [comment]
I also tried taking the batteries out and in on each if that makes a difference somehow.

**Comment by cathery** [comment]
Can you try downloading one of the earliest versions of the sysmodule (0.2.0, 0.2.1) and see if the elite controller works there?

**Comment by Lockheed-Martini** [comment]
Tried both. These did not even recognize the controllers with the icon or inputs. Seemed like they where not noticed at all on both versions. again tried 2 regular and 3 elite.

**Comment by cathery** [comment]
That's weird. There was video proof showcasing an Xbox One Elite controller working just fine even with the earliest release of sys-con: https://www.youtube.com/watch?v=3Cxwyl1xYCE

The elite controller that was recognized even has the same vendor/product IDs as yours. Only explanation I can see is that a firmware update got installed to all of your xbox controllers which requires a different setup packet to be sent before it starts sending any input.

**Comment by Lockheed-Martini** [comment]
maybe i can try updating mine. you think CFW matters?

**Comment by cathery** [comment]
Switch CFW doesn't matter. If your controllers are on the latest update I don't think you can go back. But you could try, not like it gets any worse than this

**Comment by cathery** [comment]
Actually maybe I could update my controller and see too

**Comment by cathery** [comment]
Mine is up to date. Firmware 3.1.1221.0

**Comment by Lockheed-Martini** [comment]
![image](https://user-images.githubusercontent.com/57572931/68539149-e0ec0100-0333-11ea-9417-854f7205e27e.png)

![image](https://user-images.githubusercontent.com/57572931/68539153-f19c7700-0333-11ea-9f32-b7b92df8d660.png)


my elite controllers where up to date but the normal controller did receive an update.

**Comment by cathery** [comment]
Do any of the builds that weren't working with the normal controllers work now?

**Comment by Lockheed-Martini** [comment]
tried the last build you sent and no, same thing with normal. my elite controller had no update so obviously no change. really wondering what that guy with the videos different variable was.

**Comment by cathery** [comment]
Try this version https://files.catbox.moe/3o3431.rar

**Comment by atmanli** [comment]
Hey,
I have the same issue as @Lockheed-Martini .
I tried every version posted here and it is not working.

**Comment by atmanli** [comment]
btw: the log throws out this:

> 2019-10-10 00:00:00: Succeeded event 1118
> 2019-10-10 00:00:00: Interfaces size: 0; capacity: 8
> 2019-10-10 00:00:00: Error creating interface for product 739 with error 69
> 2019-10-10 00:00:00: Interface state was changed

**Comment by cathery** [comment]
This is not 0.4.1. You're using an old version. Make sure the file located at `/atmosphere/titles/690000000000000D/exefs.nsp` is replaced.

**Comment by atmanli** [comment]
I see. I just deleted the folder and moved extracted the archive.
Looks like v041 doesn't create a log.txt at all.
Icon is showing up, but no input is recognized.

**Comment by atmanli** [comment]
v0.2.2 does seem to work.
Log output:
> New sysmodule session started
> 2019-10-10 00:00:00: Successfully created event 1118
> 2019-10-10 00:00:00: Successfully created event 1356
> 2019-10-10 00:00:00: Succeeded event 1118
> 2019-10-10 00:00:00: Interfaces size: 0; capacity: 8
> 2019-10-10 00:00:00: Interface created successfully on product 739

**Comment by cathery** [comment]
Works as in, it reads input? Or just the icon?

**Comment by atmanli** [comment]
It works flawlessly :)

**Comment by cathery** [comment]
Thanks for your feedback, we're finally getting somewhere. 0.4.1 changed the log location to `sdmc:/config/sys-con/log.txt`, can you send me its output?

**Comment by atmanli** [comment]
log of v0.4.1 (although it states 0.4.0):

> New sysmodule session started on version 0.4.0
> 2019-10-10 00:00:00: Successfully created event for Dualshock 3
> 2019-10-10 00:00:00: Successfully created catch-all event
> 2019-10-10 00:00:00: Catch-all event went off
> 2019-10-10 00:00:00: Catch-all event went off
> 2019-10-10 00:00:00: Catch-all event went off
> 2019-10-10 00:00:00: Registering Xbox One controller
> 2019-10-10 00:00:00: Send a specific init packet for controller v1118 p739 with outPacket 0
> 2019-10-10 00:00:00: Interface created successfully
>

**Comment by cathery** [comment]
That's really weird. There's only one thing that could be possibly different between these versions and I removed it, try it now: https://files.catbox.moe/g7u6sx.rar

**Comment by cathery** [comment]
wait no

**Comment by cathery** [comment]
This build should be identical to 0.2.2: https://files.catbox.moe/jwliyq.rar

**Comment by atmanli** [comment]
The build you posted last is still working

**Comment by cathery** [comment]
Oh great! Have you tried the one i posted before it, by chance? does it work there?

**Comment by atmanli** [comment]
Just tested it. Build g7u6sx.rar is also working!

**Comment by Lockheed-Martini** [comment]
> 
> 
> Try this version https://files.catbox.moe/3o3431.rar

Going through the responses, tried this one and normal works great elite just noticed.
 
> 
> 
> This build should be identical to 0.2.2: https://files.catbox.moe/jwliyq.rar

OH BOY. 
 tried this one and it works!!!!

**Comment by cathery** [comment]
holy crap!!

**Comment by cathery** [comment]
This will be the last build to test. Does everything work in it still? https://files.catbox.moe/ucmflq.rar

**Comment by Lockheed-Martini** [comment]
Works great! 
one thing i noticed but maybe it was nothing. I plugged elite in and it showed up but no inputs worked. Unplugged and plugged back in and it worked! 
I also tried normal controller and docked and portable and all is working great!

Seriously thank you for your hard work man this is awesome, so happy i  can use my favorite controller!

**Comment by cathery** [comment]
Huh alright. If you unplug all your controllers and restart the console, does it still need to be plugged in twice for it to work?

**Comment by Lockheed-Martini** [comment]
after a restart and plugging it back in it worked perfect first try.

**Comment by cathery** [comment]
Nice. I'll use this version in the release

**Comment by Monkeor** [comment]
I'm sorry to say this so soon after a presumed solution was found, but that latest build is giving me identical errors with an Elitev1 controller. Plugging it in has the switch recognize it as a pro controller, but none of the inputs work. :\

**Comment by cathery** [comment]
Does this one work? https://files.catbox.moe/jwliyq.rar

**Comment by Monkeor** [comment]
I'm... embarrassed to say that I'd somehow mixed up the files from latest build you shared with those of an earlier one. The 'ucmflq' build works entirely. Apologies for the false flagging.

**Comment by cathery** [comment]
Good. I'm so relieved
