### ISSUE TITLE
issue with SpeedLink Torid controller 

### ISSUE THREAD

**Issue by jinx23m** [cathery/sys-con#52]
hey 

first of all thank you for the hard work 
your the best 

second question is i got issue with SpeedLink Torid controller  
the switch didn't recognized him 
its a connection with a USB Bluetooth (its working on my pc and ps3)
the question if it can work on the switch with sys-con?

i installed the new version of sys-con 0.4.1

thank you master

**Comment by cathery** [comment]
There's no bluetooth support yet. Check pinned issues

**Comment by jinx23m** [comment]
oh thank you
