### ISSUE TITLE
Original Xbox Controller: The Slim version crashes the console but the Duke doesn't

### ISSUE THREAD

**Issue by Milo721** [cathery/sys-con#54]
As title, if I plug the Slim controller the Switch crash, the Duke doesn't make the console crash.
Both of them works on OG Xbox.

**Comment by cathery** [comment]
Does it crash without the sysmodule enabled? If it doesn't, can you launch this diagnostics applet and send me a scan of your slim controller? https://files.catbox.moe/re60qo.rar

**Comment by Milo721** [comment]
It crash even without the sysmodule.

**Comment by cathery** [comment]
Nothing I can do to help then, must be a problem with your OFW/CFW
