### ISSUE TITLE
Third party XBOX 360 dongle support

### ISSUE THREAD

**Issue by salimassaf** [cathery/sys-con#55]
Is it possible to get this working on a third part Xbox 360 dongle?

Vendor:045e Product:0291

The applet screetnshot can be found by checking AnthonyTorres58's post in the thread below
https://github.com/cathery/sys-con/issues/11 

I tested it with the current build, and it did nothing seemed to work.

**Comment by cathery** [comment]
It should work. Unless this update broke every single dongle, It's your manufacturer's fault for not implementing it properly. The vendor + product indicate an official microsoft wireless receiver. Also, you may just not have installed the sysmodule properly. Make sure you replace the file located at `sdmc:/atmosphere/titles/690000000000000D/exefs.nsp`

**Comment by salimassaf** [comment]
Sorry – I didn’t realize that this works only on hacked versions of switches.  I was trying it on an unhacked version I just bought.

Thanks for the help anyway.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
