### ISSUE TITLE
HORI Fighting Stick Mini 4 - Analog Stick

### ISSUE THREAD

**Issue by caiofcabral** [cathery/sys-con#57]
Works well with D-pad control, but in games like SSBU, the analog stick emulations doesn`t work.
Is the any option to config?

**Comment by cathery** [comment]
There's an option in the config file to swap D-pad and analog stick controls. set `swap_dpad_and_lstick` from `false` to `true` in what i'm assuming is the dualshock 3 settings

**Comment by MrMiralok** [comment]
How did you connect HORI Fighting Stick? I can not.
