### ISSUE TITLE
crash when playing with wired xb one controller

### ISSUE THREAD

**Issue by q350976501** [cathery/sys-con#61]
tks for the this plugin
it can work fine with my TXOS, until about 10 to 20min later the system reports a crash then automatically close my running xci game, with no time for me to even make a save. 
it's devastating, I tried twice and still get the same result
hoped to get some advise here
tks again

**Comment by cathery** [comment]
Don't use TXOS then.

**Comment by q350976501** [comment]
> Don't use TXOS then.

hmm……

**Comment by cathery** [comment]
[This is the first result i get when i google "TXOS"](https://team-xecuter.com/community/threads/txos-crash-with-external-usb-bluetooth-adapter.131764/)
I highly doubt it's an issue with my sysmodule. Prove me wrong

**Comment by q350976501** [comment]
> [This is the first result i get when i google "TXOS"](https://team-xecuter.com/community/threads/txos-crash-with-external-usb-bluetooth-adapter.131764/)
> I highly doubt it's an issue with my sysmodule. Prove me wrong

it may make sense when others reported without mentioned CTW
I tried a few more times after that，and get the same results. The crash just repeat，without solid time or place or certain button combination. But if I pull out my xbox controller，and play with orgin joy-stick，nothing went wrong as usual.
However, what i highly doubt is ur sysmodule combine with my XCI game Xenoblade，it is a so-called fusion version with all DLC and upd in an XCI profile，or it just mismatch with other sysmodule and crash i think
next time im trying other NSP games or maybe i can run the diagnostics app for a try?

**Comment by cathery** [comment]
Try disabling my sysmodule and plugging your xbox controller for a while.

**Comment by q350976501** [comment]
> Try disabling my sysmodule and plugging your xbox controller for a while.

i figured out

**Comment by q350976501** [comment]
> Try disabling my sysmodule and plugging your xbox controller for a while.

xenoblade is the only game get crashed with ur sysmodule，others won't.
And I have played this game for more than 20h before without  ur sysmodule

**Comment by cathery** [comment]
Are you running other sysmodules? There's not enough memory to run all of them at once and your game runs out of memory eventually

**Comment by q350976501** [comment]
> Are you running other sysmodules? There's not enough memory to run all of them at once and your game runs out of memory eventually

i only have one other sysmoudle called AutoLoader for TXOS，maybe u r right, i will get the chance to try more games and report to u
