### ISSUE TITLE
Can't build from source.

### ISSUE THREAD

**Issue by SuperPichu** [cathery/sys-con#62]
I'm attempting to build this from source to test a custom device. I have devkitpro set up and I can build all the examples. However when I attempt to build this project is throws some dependency errors.
Any help would be appreciated.
```
make -f MakefileSysmodule
```
output is attached.
[output.txt](https://github.com/cathery/sys-con/files/3837251/output.txt)

**Comment by cathery** [comment]
Sorry that there's no guide on building it right now, the sysmodule uses the libnx build from the repo (not released yet), so you'd have to build it first

**Comment by SuperPichu** [comment]
That explains a lot. thanks.

**Comment by cathery** [comment]
Just added instructions to the main page
