### ISSUE TITLE
Power-A Xbox One controller doesn't work

### ISSUE THREAD

**Issue by DrHacknik** [cathery/sys-con#64]
The controller does connect, and tries register properly; although it will disconnect every so often, and no inputs will register (Except L and R for some reason) 

On latest Atmosphere, AMS 9.0.1 and 0.4 sys-con

**Comment by cathery** [comment]
I've tried to fix this issue for Power-A controllers in 0.4.2, does it still persist?

**Comment by DrHacknik** [comment]
Yes it does work fine it seems. Just the buttons are mapped like a Nintendo controller. I'm pretty sure that can be configured correct?

**Comment by cathery** [comment]
Yeah, in the config file for xbox one controller. I'm very relieved it's working

**Comment by DrHacknik** [comment]
Alright, thanks for the help. I thought 0.4 was the latest since it hasn't been updated on the HB Appstore yet.
