### ISSUE TITLE
Recognize as GameCube controller to use analog trigger

### ISSUE THREAD

**Issue by 90luke90** [cathery/sys-con#66]
Is there any way to recognize an USB controller e.g. xbox 360 as gamecube controller to use the analog trigger?
The game GRID does support the gamecube controller to use the analog trigger to brake and accelerate. It would be nice to configure each controller as what they should be recognized.

**Comment by cathery** [comment]
Maybe it's possible. No need to recognize it as a gamecube controller. Currently all controllers just pass the binary value on/off for triggers. I need to look into it

**Comment by cathery** [comment]
I will continue the discussion in #39
