### ISSUE TITLE
Rock Candy 360 controller does not work

### ISSUE THREAD

**Issue by AlexS2412** [cathery/sys-con#7]
tried to use it and it does not work. however ds3 controller worled flawlessy, cant wait for rumble!

**Comment by cathery** [comment]
Can you see if it works on this build? https://files.catbox.moe/5zbqou.rar

**Comment by Roulio78** [comment]
Same problem with Rock Candy 360. I've also tried what you sent; but it still doesn't work.
Thank you for your work by the way. Will you do the same with PS4 controller ?
Thank's :)

**Comment by Roulio78** [comment]
Do you have Paypal ? I could send you money by Paypal

**Comment by cathery** [comment]
There's a link to my ko-fi at the bottom of my info page. Does rock candy 360 work on version 0.4.0?

**Comment by Roulio78** [comment]
I'm sorry but I don't I know. Give me instructions, i can follow it

**Comment by cathery** [comment]
Download the latest release [0.4.0](https://github.com/cathery/sys-con/releases/tag/0.4.0) and install it like usual. Does it get recognized by the switch? Do the inputs work?

**Comment by Roulio78** [comment]
I did it but it still doesn't work. The Xbox central button is flashing, and the Switch don't recognize the controller

**Comment by cathery** [comment]
Alright, can you launch this applet and send me a scan of your controller? https://files.catbox.moe/re60qo.rar
You put the nro file in `sdmc:/switch/` and launch it from the homebrew menu

**Comment by Roulio78** [comment]
![2019110915324400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/57547098/68530191-71abe800-0306-11ea-88c7-8a7df6915dda.jpg)

**Comment by cathery** [comment]
That seems almost identical to the official xbox 360 controller. It should at least get recognized by the switch. Can you send me the log? It's located at `sdmc:/config/sys-con/log.txt`

**Comment by Roulio78** [comment]
[log.txt](https://github.com/cathery/sys-con/files/3827408/log.txt)

**Comment by cathery** [comment]
I'm sorry... You're using an old version of the sysmodule. Download the latest release and make sure you replace the file located at `sdmc:/atmosphere/titles/690000000000000D/exefs.nsp`

**Comment by Roulio78** [comment]
yaaaaay it works ! It was because I had 2 sys-con ! I didn't remove the old version and just added the latest version. Thank you so much :)

**Comment by cathery** [comment]
Alright, @AlexS2412 let me know if your Rock Candy 360 works so I can close this issue

**Comment by yuesergio** [comment]
does not recognize the controls of the Xbox 360 with charge and play kit
