### ISSUE TITLE
Y button on Dualshock 4 does not work

### ISSUE THREAD

**Issue by ameer-h** [cathery/sys-con#71]
Y button does not register input

**Comment by Dantenerosas** [comment]
I've tried latest release and Y button works perfectly with my Rev 1 DS4

**Comment by zeldaism** [comment]
Using latest version too and the Y button works on my rev 2 DS4

**Comment by Sumpftier** [comment]
I used a knock off v2 ds4 and had a lot of random missinputs

**Comment by 11five** [comment]
Am I doing something wrong when connecting it? I have the CUH-ZCT2U model and I tried changing it to true and false but it isn’t connecting l??

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameer-h** [comment]
Sorry guys about the false alarm. It seems my PS4 controller is busted. Hadn't used it in a bit.
