### ISSUE TITLE
Crashing when in sleep mode.

### ISSUE THREAD

**Issue by romulopereira** [cathery/sys-con#73]
I'm using the xbox 360 wireless adapter and from time to time the switch crashes without doing anything. In sleep mode.

It gives me an error code 2162-0002 (0x4a2) on title 0100000000000023.

I'm on firmware 9.0.1 on atmosphere 0.9.4 and I don't have other sysmodule installed.

**Comment by cathery** [comment]
Which sys-con version are you using? Does it crash without the 360 wireless adapter plugged in?

**Comment by romulopereira** [comment]
I'm using version 5.0 now but it happens with version 0.4.2 too.

I'm testing without the adapter now, but in an hour without it doesn't crashed yet.

Can I do anything to help?

**Comment by cathery** [comment]
Ah alright, did it crash with any other controllers? Also, can you install 0.4.0 and see if it crashes there too?

**Comment by romulopereira** [comment]
I don't know if it crashes with other controllers alone. I tested with dualshock 4 and the adapter plugged and it crashed. I'm stalling 0.4.0 now to test.

**Comment by cathery** [comment]
Also just for testing purposes, the switch has a tendency to wake up the sysmodules 1 or 2 times before entering deep sleep, so if there's a crash, it should happen within one minute after going to sleep mode

**Comment by romulopereira** [comment]
So, not crashed yet. When deep sleep exactly happens? It's just when I put the switch on dock with screen off?

**Comment by cathery** [comment]
Deep sleep happens one minute after you go to sleep, docked or undocked. If it crashes even later than that it's gonna be a very difficult situation.

**Comment by jphan0** [comment]
I can confirm that this does happen to me as well, and that it does happen way after one minute. Running 8.1.0 on AMS 0.9.4 with sys-con 0.5 using the official wireless dongle for PC and an official 360 controller. To reproduce just put it into sleep mode with the controller still connected. Seems to happen >15 minutes randomly.

**Comment by SmartBoy84** [comment]
I know this doesn't help but in what case would you need the controller connected when put in deep sleep?
Personally the solution seems fairly simple - unplug?
Maybe let cathery focus on other things?

**Comment by cathery** [comment]
I'm trying a new build - can someone test if it crashes in sleep mode with 360 dongle plugged in? https://files.catbox.moe/47x1cv.rar

**Comment by romulopereira** [comment]
Testing for around 3 hours. Not crashed yet.

**Comment by cathery** [comment]
Alright, I'm going to assume this has fixed it

**Comment by romulopereira** [comment]
Yeah. Still don't crashed.
