### ISSUE TITLE
Disable a specific USB port

### ISSUE THREAD

**Issue by mario-donnarumma** [cathery/sys-con#74]
Is it possible to disable a specific USB port so that sys-con doesn't not try to recognize anything connected to it? In this way we could safely plug any adapter into the Switch and avoid possible conflicts (I'm having problems with the 8bitdo adapter as mentioned by others but I imagine this could happen with other adapters too)

**Comment by cathery** [comment]
I don't believe so - the switch relies on accepting devices from any port. If there was a way to disable a specific USB port, it would not be recognized by the sysmodule or the switch in general.

**Comment by mario-donnarumma** [comment]
Alright, got the point (thank you for your effort by the way).
