### ISSUE TITLE
Dualshock4 hot-plugging not working

### ISSUE THREAD

**Issue by MrRumpel** [cathery/sys-con#75]
Some game need motion control,so I try remove ds4.
But hot-plugging ds4 is not working.
Reboot switch it's work.

**Comment by MrRumpel** [comment]
New sysmodule session started on version 0.5.0
2019-10-16 16:59:00: Successfully created event for Dualshock 3
2019-10-16 16:59:00: Successfully created catch-all event
2019-10-16 16:59:00: Successfully created event for Dualshock 4 0x9cc
2019-10-16 16:59:00: Catch-all event went off
2019-10-16 16:59:00: Dualshock 4 event went off
2019-10-16 16:59:00: Registering DS4 controller
2019-10-16 16:59:00: Interface created successfully
2019-10-16 16:59:00: Interface state was changed
2019-10-16 17:02:56: Erasing controller! 6
2019-10-16 17:02:56: Controller erased!
2019-10-16 17:02:56: Catch-all event went off
2019-10-16 17:22:02: Dualshock 4 event went off
2019-10-16 17:22:02: Registering DS4 controller
2019-10-16 17:22:02: Interface created successfully
2019-10-16 17:22:02: Interface state was changed
2019-10-16 17:23:00: Erasing controller! 6
2019-10-16 17:23:00: Controller erased!

**Comment by cathery** [comment]
Sometimes dualshock 3/4 controllers will not be recognized by the sysmodule - this is an issue with the workaround I'm using. And yeah your best bet is to reboot your switch

**Comment by 11five** [comment]
>Sometimes dualshock 3/4 controllers will not be recognized by the sysmodule - this is an issue with the workaround I'm using. And yeah your best bet is to reboot your switch

@cathery I’ve tried setting the global.ini setting to true & false but my controller doesn’t work. My DS4 model is CUH-ZCT2U I don’t even think I needed to change the global settings. I rebooted too but it’s not working.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cathery** [comment]
@11five send me a screenshot of the scan from this applet https://files.catbox.moe/re60qo.rar

**Comment by 11five** [comment]
@cathery sorry, I’m new to GitHub. Not sure what scan you mean? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cathery** [comment]
Download this applet and launch it on your switch. Press Y while your controller is plugged in and take a screenshot

**Comment by 11five** [comment]
Alright gotcha

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cualquiercosa327** [comment]
Hello,i dont know if it help but mine also did no worked. (The first was change to true on default config).
Some tries and reset switch before,i pasted the one cathery post on the thread i created ,reset the switch and it began to work without problem.
I dont know why (maybe the spaces ?) no sure,but i recomend you try.
Good Luck!

**Comment by JonJaded** [comment]
![2019111801391500-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/35312501/69029991-51ce9100-09a4-11ea-82e2-1458e02ef0ea.jpg)

Since 11five never responded with a screenshot, I decided to with my CUH-ZCT2U controller. Sometimes it's detected, and some times it's not. What I do know is that CUH-ZCT2U is a second gen controller (front-facing lightstrip) and it only works if the 2nd generation controller thing is set to true in the global ini.

**Comment by cathery** [comment]
Your controller is the same as mine. I don't know how you guys do it, try copying my version of the global config file

[config_global.zip](https://github.com/cathery/sys-con/files/3854705/config_global.zip)

**Comment by 11five** [comment]
>Hello,i dont know if it help but mine also did no worked. (The first was change to true on default config). ...

@cualquiercosa327 how do I reset switch? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cualquiercosa327** [comment]
hello,i explain bad: i mean reboot.
You only need to change the file for the attached and reboot the switch.
