### ISSUE TITLE
Xenoblade Chronicles 2 crashes in-game when controller is connected

### ISSUE THREAD

**Issue by Dantenerosas** [cathery/sys-con#76]
FW 9.0.1, Atmos 0.9.4
In main menu everything is fine but it crashes mere seconds after you load game. Doesn't matter whether controller was connected before launching the game or after loading save.
Tested this with DS3 and DS4

**Comment by cathery** [comment]
Are you running other sysmodules?

**Comment by Dantenerosas** [comment]
Only sys-clk and ldn_mitm

**Comment by cathery** [comment]
Does it still crash if you disable them?

**Comment by Dantenerosas** [comment]
Yes, it still crashes when both are disabled. I've disabled sys-clk from sys-clk-manager and "disabled" ldn_mitm by removing folder (because for whatever reason config app always shows that it is on after reboot). Doesn't seem like it really matters whether they are on or off

**Comment by Dantenerosas** [comment]
I feel obliged to say that I've returned my copy of the game to the store (long story short, didn't like it) so if you will need to test whether fix for this works or not you will need to find someone else who has copy of XB2 and also has same crashes
