### ISSUE TITLE
Chaotic inputs sometimes when connecting multiple different controllers

### ISSUE THREAD

**Issue by Dantenerosas** [cathery/sys-con#78]
I've encountered this just now when tried to connect 2 Rev 1 DS4 and 1 DS3 at the same time to play some Smash. After that I've tried various variants of connecting and it seems if all connected controllers are the same everything is fine but whenever you connect another type (for example, DS4 first and DS3 second) then input may go haywire aka turbo pressing every button there is. This behavior seems to go away if you disconnect last connected controllers and then connect it again.
Also, strangely enough, it seems like if DS3 was connected first and then you connect 1 DS4 then everything will be fine. But input may go haywire if you connect another DS4 (total 3 controllers)

**Comment by cathery** [comment]
I just tried what you told me and it happens for me too. Plugged in DS4 -> plugged in DS3 -> unplugged DS3 -> plugged DS3 again and got the chaotic inputs. I'm not sure what's causing it

**Comment by Dantenerosas** [comment]
It can be simpler chain of events tho. For me it also sometimes happens if you connect DS4 first and then DS3 without any additional unplugging/plugging.

**Comment by cualquiercosa327** [comment]
Hello,i have reading the code  (maybe my comment is silly) but i think the problem could be on  GetInput() from Ds4 ,in concrete on 

#ifdef __APPLET__
    for (int i = 0; i != 64; ++i)
        m_inputData[i] = input_bytes[i];
    m_UpdateCalled = true;
#endif

Sorry : it is late and i am almost asleep .Tomorrow i will read it again trying to found why
