### ISSUE TITLE
Request-Problems and some curiosity

### ISSUE THREAD

**Issue by cualquiercosa327** [cathery/sys-con#80]
Hello,first say you thank you for your great program : i have diferent gamepad and could use it on Switch is amazing.

My request is if could be some kind of program/ui which let us configure and create profiles on gamepads, i mean if it would be posible we can help you adding hid support as it happen with hid to vpad for wii u and the app which let us see the vid/pid to add support more pads (in concrete "clones").
Later it could be somekind as the UI (similar to https://github.com/kozec/sc-controller.)
I have though to make a request of it to uLaunch which could be more apropiate .

About the problem i had tried to use several pads but i was unable with most of them until now**.Before create a request i decided see the similar Issues , in concrete the one for xbox one (https://github.com/cathery/sys-con/issues/51 ) and the dualshock4 (https://github.com/cathery/sys-con/issues/75).
I read them and save the programs you post to test (diferent compilation of your program you post on Xbox one Elite and deviceDiagnostic from the Dualshock4 issue thread.

it has been very strange : i have the  latest version installed but the Elite did no worked.
i replaced it with the latest compilation you post on Xbox one and it began to work with some problems (only worked the analog ).I put again the latest version,restart the switch and it began to work flawless!

With the DS4 v2 i tried with "false" and  "true" on config as you recommend but it doesnt work.

I have also 2 dualshock3 clones :  one is a Gioteck which have a usb to plug for working.
The most curious it works great on MAGIC-NS Wireless & Wired Controller Adapter (The device see it as Wired ) but you program did no see it.

The other works great with your program.

I attach the picture i took with your  deviceDiagnostic program with the Dualshock4 and the latest log where i conect all the controllers (and it works great the Xbox Elite v1 and one of the DS3 Clone both also at same time).(Also i add the first log when the Xbox Elite v1 did no work : maybe it could help you to found why it happen to other people)
[log 0.txt](https://github.com/cathery/sys-con/files/3854648/log.0.txt)
[log-latest.txt](https://github.com/cathery/sys-con/files/3854649/log-latest.txt)
![Ds4](https://user-images.githubusercontent.com/16308276/68998874-35edc100-08b8-11ea-812b-5d5f3a2f4f97.jpg)

if it would be posible ,i would love could use the Gioteck's Dualshock 3 clone with usb because this way i could use two wireless : this with your program and DS4 with Myflash adapter.
Thank you for everything

**Comment by cathery** [comment]
I have the same dualshock 4 as you. I have to set the global setting for dualshock 4 to `true`. It should work. Here's how my global config looks like: 

[config_global.zip](https://github.com/cathery/sys-con/files/3854705/config_global.zip)

**Comment by cualquiercosa327** [comment]
hi.Interesting : this was the first i did but it did no work.
I am going to try it again now (I am posting the UI i told you on Ulauncher )
A lot of thanks

**Comment by cualquiercosa327** [comment]
wow,this is really strange because the first i did when i installed your app was change this to true but it did no work.I have just deleted and paste your file ,reset the switch and it works flawesly!!
It seems dark magic because with the Xbox one Elite v1 happened the same : from only work the analog ,replace the files for the testing one ,reset,same error,paste again the newest ,reset switch and it began to work..
Excuse me again,i attach the picture from the other Dualshock 3 clone when i put the usb on the switch,could it work? (I am no sure but i think than changing the PID / Vid it should work as it does on the Myflash adapter)

For this i made the request of could add this parameters on the fileconfigs as happen on "Hid to Vpad" which would make users could add extra controllers (as clones) without need to disturb you.
Thanks
![IMG-20191116-WA0003](https://user-images.githubusercontent.com/16308276/68999545-e7452480-08c1-11ea-8486-9bc98f68991e.jpg)
![IMG-20191116-WA0005](https://user-images.githubusercontent.com/16308276/68999546-e7452480-08c1-11ea-8686-7f80778a017c.jpg)

**Comment by cathery** [comment]
It won't work because It can't support more than 2 different controllers with an IClass of 3 right now. This is also the reason why I can't support both versions of Dualshock 4 simultaneously.

**Comment by cualquiercosa327** [comment]
Ah,ok.
Excuse me for repeating,but could no be added this parameters (IClass ,vid,pid) on the controllers config file?
You can see it  here :
https://github.com/Maschell/controller_patcher/wiki

**Comment by cualquiercosa327** [comment]
Hi again,i am trying reading your code but i dont found what i should change (I would prefer could use the gamepad  i posted better than original ds3 or the clone i own than works perfect because it let me be without wired).
I think the issues should be on 
ControllerUSB/include/ControllerTypes.h
and
ControllerUSB/include/Controllers/Dualshock3Controller.h
but i dont found the variables i should change.The Vid and Pid are under a comment.
Excuse me for disturbing you
Thanks

**Comment by cualquiercosa327** [comment]
Hello,i am trying to make it work myself but i have some questions/doubts. how could we chat ? Thanks.

**Comment by cualquiercosa327** [comment]
Hello,i have fork your code and create (replying what you did for two versions of ds4) some code for allow some ds3 clones.The problem is i can no compile it .Could you compile my fork? 
A lot of thanks and excuse me

**Comment by cathery** [comment]
Please stop spamming in every issue if you don't know what you're doing.
