### ISSUE TITLE
Request - xbox 360 wireless controller to turn itself off when switch goes to sleep mode

### ISSUE THREAD

**Issue by elephantdino** [cathery/sys-con#84]
currently, the xbox 360 wireless controller tries endlessly to resync with the Switch after it has gone to sleep. I don't know when it will turn itself off without pulling out the battery pack.

**Comment by cathery** [comment]
Does the controller turn off in the latest version [0.5.1](https://github.com/cathery/sys-con/releases/tag/v0.5.1)?

**Comment by BlackomegaTM** [comment]
Yes, the controllers turn of when the console enters sleep mode. Still, they won't turn the console on from sleep.

**Comment by cathery** [comment]
That makes sense, because the console puts USB to sleep. You probably can though, during a very short interval, when the switch temporarily wakes it up .
