### ISSUE TITLE
Dualshock 4 doesn't work

### ISSUE THREAD

**Issue by Roulio78** [cathery/sys-con#87]
Hey, thank's a lot for your work !
I have a problem with my Dualshock 4, a first generation, there is no detection :/

Here the log : 
[log.txt](https://github.com/cathery/sys-con/files/3859938/log.txt)

Here the device diagnostic :
![2019111818452800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/57547098/69076641-2f845400-0a34-11ea-87b9-6eb62f9308a7.jpg)

**Comment by cathery** [comment]
That's not a Dualshock 4. That's a mass storage device.

**Comment by Roulio78** [comment]
How am I suppose to connect the DS4 ? With a USB cable, like if I were recharging the controller right ?

**Comment by Roulio78** [comment]
I retried and retried, and it still doesn't work :/

**Comment by Roulio78** [comment]
Hey,
Why did you closed ? I'm sorry but I really need your help ^^
I offered you a coffee, I'll pay a second if you solve the issue.
Thank's ^^

**Comment by cathery** [comment]
Like I said earlier, what you have on the screenshot is not a dualshock 4. It's a Genesys Logic Card Reader. I can't really help you without being physically there. Maybe your dualshock is not genuine or just special, I'm unable to help. You'll have to figure it out yourself
