### ISSUE TITLE
Feature Request | Ability to change PS4 lightbar colour

### ISSUE THREAD

**Issue by HoneyOTU1337** [cathery/sys-con#88]
title.

**Comment by cathery** [comment]
I'm considering it

**Comment by cualquiercosa327** [comment]
hello,could it be the lightbar off? Thanks

**Comment by HoneyOTU1337** [comment]
i agree, the ability to change how dim or completely turn off the lightbar would be neat

**Comment by cathery** [comment]
Added in [0.5.1](https://github.com/cathery/sys-con/releases/tag/v0.5.1)
