### ISSUE TITLE
More than 2 xbox controllers results in error 11037

### ISSUE THREAD

**Issue by vinnyzer0** [cathery/sys-con#89]
When attempting to connect 4 Xbox One controllers to my switch, "Error creating interface with error 11037" is thrown.

The controller vibrates when plugged in, but the xbox icon blinks white unlike the two that were first plugged in which stay static white.

Here's the full log of a controller being plugged in then getting an error:
2019-10-20 14:54:52: Registering Xbox One controller
2019-10-20 14:54:52: Error creating interface with error 11037
2019-10-20 14:54:52: Interface state was changed
2019-10-20 14:54:52: Catch-all event went off

I'm on Atmosphere 0.9.4, system version 9.0.1.  No emu-nand

**Comment by cathery** [comment]
Seems like a really weird issue. Does that happen when you plug in the second controller, or when 2 are already connected and you try to plug in the third?

**Comment by vinnyzer0** [comment]
It happens when there are already two connected and functioning, and attempting to add a third one.
