### ISSUE TITLE
SXOS can not use it?

### ISSUE THREAD

**Issue by lulupk250** [cathery/sys-con#95]
SXOS can not use it?

**Comment by ipodtouchdude** [comment]
You can use it on SXOS as I am. Just rename atmosphere folder to sxos. So it will then look like sxox/titles/690000000000000D (basically just place the 690000000000000D in the sxos/titles folder) and the config folder to the root of the SD card and then reboot.

**Comment by deenasty** [comment]
> You can use it on SXOS as I am. Just rename atmosphere folder to sxos. So it will then look like sxox/titles/690000000000000D (basically just place the 690000000000000D in the sxos/titles folder) and the config folder to the root of the SD card and then reboot.

Hi, thank you for your help. I have done exactly what you described but still not working.
