### ISSUE TITLE
Please, add this other new ID to x360 driver

### ISSUE THREAD

**Issue by hostfer** [cathery/sys-con#97]
Hello from Spain, can you add this other usb ID to your xbox controller? Its a genuine receiver pcb from red lights xbox hardware, in windows works with the same driver as the oficial receiver only changing the ID in the .inf file (the arduino is only for sincync and lights, but if you already have sincync it in the past, isn´t necesary): 

Info of this project:
https://duino4projects.com/diy-xbox-wireless-controller-adapter-for-pc/

Original:
%XUSB21.DeviceName.Wired%=CC_Install, USB\**Vid_045E&Pid_028E**
%XUSB21.DeviceName%=CC_Install, USB\**Vid_045E&Pid_0719**

Diy version:
%XUSB21.DeviceName.Wired%=CC_Install, USB\**Vid_045E&Pid_0291**
%XUSB21.DeviceName%=CC_Install, USB\**Vid_045E&Pid_0291**

**Comment by cathery** [comment]
sys-con doesn't check VID or PID for XInput devices.

**Comment by hostfer** [comment]
It´s really! I test it now and works at the first time, very good news to same users.

Sound ridiculous, but i not tested in the past why i can´t imagine this old pcb works plug and play with your sys-con, very good project and sorry!
