### ISSUE TITLE
Xbox One controller regular vibrations

### ISSUE THREAD

**Issue by mzino** [cathery/sys-con#98]
When using an Xbox One controller (the most recent version with Bluetooth support, if it matters) via USB in docked mode, after putting the console in standby the controller continues emitting short vibrations at regular intervals about 8s apart, as long as it's plugged in.
I honestly don't know if this is normal, if it's a problem with the controller or if it's related to sys-con, and I can't find any info about it. It only happens with Switch.

EDIT: since it's the same behavior that happens when plugging it into a phone charger, could it be that the Switch's dock is regularly turning on and off the USB port? Could this be controllable with sys-con?

**Comment by deadair3210** [comment]
I know that the same thing happens when I plug my switch into my computer with USB c and it goes to sleep so maybe you are on to something with the cause

**Comment by cathery** [comment]
What? There's no Bluetooth support for Xbox One controller. The Cradle (switch's dock) constantly gives power to the Xbox One controller, causing it to vibrate every so often. As proof, you could remove the switch from the dock completely and it will still vibrate, given it has power.
