### ISSUE TITLE
Steam Controller Support

### ISSUE THREAD

**Issue by y0shin** [cathery/sys-con#99]
With the Steam Controller going on sale(plus costing next to nothing on the 2nd hand market) I feel like support would be nice.

**Comment by Molina2005** [comment]
I was going to ask for that. The truth is that it is now on offer for about € 19 and it would be incredible that support could be added to Switch. Although sometimes it is complicated to be a touchpad..

**Comment by cathery** [comment]
Completely unrelated to adding support but I can't seem to find anywhere I can buy it. The steam page doesn't give me an option and the official retailer just redirects me to the home page. I guess i'm SOL

**Comment by Sumpftier** [comment]
Try buying an used one.
I just ordered one a minute ago :)

**Comment by Sumpftier** [comment]
I would love to see support

**Comment by Moxinilian** [comment]
I successfully ordered one a moment ago on the Steam Store. Perhaps you could try again?

**Comment by cualquiercosa327** [comment]
Hello,it seems they are new Steam Controllers available again.
If you are no able to buy ,i could buy one  for you and put your address.

**Comment by cathery** [comment]
Any discussion shall be continued in #35
